### PR TITLE
Fixes for checking single metadata files, docs (OpenCPN#2031)

### PR DESCRIPTION
**Pull request by leamas**
EDIT: Updated the PR which now 
  - Removes illegal archs  and targets (https://github.com/OpenCPN/OpenCPN/issues/2003)
  - Fixes for check-metadata-urls to accept a single metadata file.
  - Fixes for pre-commit to also check urls.
  - Add a check-urls Makefile convenience target.
  - Documentation updates, partly after discussions in https://github.com/OpenCPN/OpenCPN/issues/2031. This PR should close that discussion.
EDIT2: 
  - Improves parsing  error messages from ocpn-metadata
EDIT3:
  - Fix for xsd schema so it can be used to validate a single plugin metadata file.
EDIT4:
  - Add xsd support for data-only plugins for all targets.
  - Let ocpn-metadata keep going on parse errors.

### CODE REVIEW

**Comment by rgleason** [comment]
You want to remove 
        print(" Processing: {path}")

when we need to know exactly what has failed somehow, by printing the failed path or filename!
We still are not given enough information to determine exactly which metadata file is wrong.
What I have to do to correct metadata files (usually  other peoples files) is laboriously move 1/2 the files to a temporary folder and run the test.  Then if it still fails move 1/2 of what is left into the temporary folder and try again.  It is trial and error moving files until the bad one is isolated. It is a PITA big time.

This applies to both urls and metadata!

**Comment by leamas** [comment]
metadata: The removed statement has been there since May, 27. However, it does not print any path, it's a plain bug. Given these two facts, it does not fill any purpose and should be removed (it *does* fill the screen with useless lines,though.)

OTOH, we could do a better job when handling the exception. Will look into that.

check-urls prints a list of broken urls like this: 
`https://dl.cloudsmith.io/public/opencpn/uktides-prod/raw/names/uktides_pi-1.0.4.0-ubuntu-x86_64-20.04-focal-gtk3-tarball/versions/v1.0.4/uktides_pi-1.0.4.0-ubuntu-x86_64-20.04-focal-gtk3.tar.gz: 404`

In this case it seems obvious that this is about the uk_tides plugin tarball url. Or? The same applies to all found broken urls. 


However: using the pre-commit hook there

**Comment by leamas** [comment]
urls: another way to find the culprit is of course using grep, something like this:

```
grep -rl 'https://dl.cloudsmith.io/public/opencpn/uktides-prod/raw/names/uktides_pi-1.0.4.0-ubuntu-x86_64-20.04-focal-gtk3-tarball/versions/v1.0.4/uktides_pi-1.0.4.0-ubuntu-x86_64-20.04-focal-gtk3.tar.gz' metadata
metadata/uktides_pi-1.0.4.0-ubuntu-x86_64-20.04-focal-gtk3.xml
```

**Comment by leamas** [comment]
PR updated. ocpn-metadata shows filename (and line number!) when parsing fails. Documentation updated again.

**Comment by leamas** [comment]
New update, ensuring that both xsd and url validadation can be used wit a single metadata file, not just ocpn-plugins.xml

**Comment by leamas** [comment]
Rebased to current master +
  - Add xsd support for data-only (no arch) plugins
  - Let ocpn-metadata keep going on parse errors

**Pull request merged**
