### PR TITLE
meta-url-alpha-seandepagnier-rgleason

### PR DESCRIPTION
**Pull request by rgleason**
Revised PR for meta-url to Sean's Alpha Plugins

The meta-url looks ok, but it looks like ocpn-plugins.xml has been reordered so there appears to be a lot of change, which I think is just switching the order.  This is a bit counter intuitiive for checking on PR's. Don't know if there is a way around that. 

PS: maybe you just want me to cut and paste the new meta-url into ocpn-plugins.xml so the order does not change?

### CODE REVIEW

**Comment by rgleason** [comment]
Should I really be deleting the rgleason:Alpha branch?  I suppose I could pull it down again.

**Comment by bdbcat** [comment]
Rick...
??  I don't understand the comment.

**Comment by rgleason** [comment]
Sorry to bother you. Github shows this:

```
Pull request successfully merged and closed
You’re all set—the rgleason:Alpha branch can be safely deleted.

```
And it conveniently has a button to Delete Branch

**Comment by bdbcat** [comment]
This message tells you that your patch has been safely merged, and all is well on the target repo. But I don't think you want to delete it.  You might want another PR against Alpha, so just roll it forward.

**Comment by rgleason** [comment]
Thank you. That confirms my understanding.

**Comment by rgleason** [comment]
PS: Added the process for Meta-Url to this Dev Manual page
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:pi_installer_opencpn_plugins

**Pull request merged**
