### PR TITLE
plugin xsd: Add new ABT darwin-wx31

### PR DESCRIPTION
**Pull request by leamas**
After discussions on email thread. Add a new ABI specification for MacOS  using wxWidtgets 3.1.5

### CODE REVIEW

**Comment by bdbcat** [comment]
I decided to use "darwin-wx315" to be ultra clear here.

**Comment by leamas** [comment]
No problem, I just filed this as a heads-up to not forget the xsd.

**Comment by jongough** [comment]
Does this mean there is no wx312 version? Are w supporting the previous version, wx302, or only the wx315 version now?

**Comment by bdbcat** [comment]
Understand that this topic applies ONLY to MacOS.
Having said that, the existing MacOS Production build for OCPN5.2.4 bundles wx312.
The plugin target specification "darwin" supports that build, i.e. wx312.
The new build for O5.6 (MacOS only) bundles wx315.  The associated plugin target is thus "darwin-wx315"

All other build targets are unaffected.

There is no need for plugins to support the existing "darwin" target any longer.  We will be shipping O56 within a few weeks. Users must move to OCPN 5.6 to get continued upgrades to their installed plugins.

**Comment by jongough** [comment]
That's fine, I am just updating testplugin to comply with the new MacOS changes. As it is used by some other plugins as the base for their builds I just want to be sure I have the bases covered. I have actually removed the wx312 version, so it looks like I need to put it back for people that are using pre O56 builds.

**Comment by bdbcat** [comment]
Jon...
You only need to "put it back" if your updates to testplugin are required on existing Production O5.2.4.
Or are you creating two separate plugin builds, with different metadata and  wx linkage rules?

**Comment by jongough** [comment]
I will probably make it a parameter such that a 'single' build will build both environments then any changes can be used on the new OCPN or the older one. It is up to those that use the frontend2 build process to decide if they want to build for both environments so I don't want to limit them until we no longer officially support a platform or release.

**Comment by rgleason** [comment]
I suppose we could keep the cloudsmith metadata from prior builds in the opencpn/plugins but it might be easier to rebuild for the earlier version of O  at the same time and use the script to add that metdata to  opencpn/plugins, so I like that option idea Jon.

**Pull request closed without merging**
