### PR TITLE
add SeanDepagnier Beta Plugins

### PR DESCRIPTION
**Pull request by rgleason**
Commit in rgleason/plugins/beta
to added new metapath to catalog.xml 
   https://raw.githubusercontent.com/rgleason/plugins/rg-beta/seandepagnier-beta-catalog.xml
This catalog is in github.com/rgleason/plugins/rg-beta/
The catalog currently contains the most recent xml files for testplugin and weather_routing so far, these tarballs are located in
https://cloudsmith.io/~rick-gleason/repos/opencpn-plugins-beta/packages/

PS I don't know if I should have renamed the ocpn-plugins.xml file to seandepagnier-beta-catalog.xml
as the python collection will not work as it currently is configured. Should I change it back?
Also, I did not want to be too specific, as the catalog will be changing as plugins are added.

### CODE REVIEW

**Comment by bdbcat** [comment]
Rick...
1.  This PR is rejected for Beta. We re not there yet. Please move to Alpha.
2.  My example was not complete.  Sorry.  You should create a new file to place in metadata/ including only the re-direct to your private metadata, then run the python tool to build a new ocpn-plugins.xml.  Then commit the results with modified ocpn-plugins, and your new metdata file added.  That way others running the python script will get your updates, and each PR will be cumulative.  I have corrected the sample in Experimental branch for reference.

**Comment by rgleason** [comment]
This is more involved than I thought. Recording for documentation. using Alpha channel.
1. In my freshly cloned local repository  github.com/rgleason/OpenCPN/plugins/Alpha
2. Under the metadata directory create a new file including only the redirect to my private metadata.
3. The filename is "meta-url-alpha-seandepagnier-rgleason.xml"
4. The text is:
```
<?xml version="1.0" encoding="UTF-8"?>
<opencpn-plugin version="1">
  <name> Sean Depagnier Alpha Plugins meta-url </name>
  <version> 1.0 </version>
  <summary> meta-url to Sean's Alpha Plugins by rgleason </summary>
    <meta-url> https://raw.githubusercontent.com/rgleason/plugins/rg-alpha/ocpn-plugins.xml </meta-url>
</opencpn-plugin>
```
5. Run the python tool to build a new ocpn-plugins.xml by executing at the command prompt from the /plugins/ directory   
`python tools/ocpn-metadata generate --force --userdir metadata --destfile ocpn-plugins.xml
`
6. Next make sure the private metadata directory is current and operational with a good ocpn-plugins.xml containing the xml data needed to direct to the cloud sources.  
7. For example I've created a new branch    
`github.com/rgleason/OpenCPN/plugins/rg-alpha `
8.  So that I can download the particular plugin  xml files from Cloudsmith and then copy and paste them into 
`github.com/rgleason/OpenCPN/plugins/rg-alpha/metadata ` 
9.  Then easily generate the necessary ocpn-plugins.xml with
`python tools/ocpn-metadata generate --force --userdir metadata --destfile ocpn-plugins.xml
`
Note order of xml data may change, causing it to appear that the PR has more changes than it actually does.

**Comment by bdbcat** [comment]
Rick...

Al sounds good, except that you will need to make a new PR for Alpha.  This one still points to Beta branch.

**Comment by bdbcat** [comment]
Rick...
Sorry, my bad.  I did not see the other PR.  Merged it, so you are good to go.
Dave

**Comment by rgleason** [comment]
I've added this process for meta-url to this Dev Manual page.
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:pi_installer_opencpn_plugins

**Pull request closed without merging**
