### PR TITLE
Jg master

### PR DESCRIPTION
**Pull request by jongough**

### CODE REVIEW

**Comment by bdbcat** [comment]
Jon...
We are standardizing on "x86_64", instead of "amd64".  This will need changing.
Also, you probably mean, for Windows builds", to use "x86-64" instead of "i386".
Thanks
Dave

**Comment by rgleason** [comment]
I guess it is not time to come out and play.

**Comment by jongough** [comment]
I have just checked oesenc, the one you held up as the example, and it still uses what I have. I don't want to make a change just to change it back as someone changes their mind. It takes me quite some time to build the plugins. So what are the definitive ARCH names?

**Comment by bdbcat** [comment]
@Jon...
Not sure what you are looking at, but never mind.
These are the accepted ARCH values:
arm64
armhf
i386
x86_64

All lower case, enforced at runtime filename checks.
@Rick...
Come out and play, its all right....

**Comment by rgleason** [comment]
Here is the way Jon has it set up.
https://github.com/jongough/testplugin_pi/blob/master/cmake/PluginSetup.cmake
With the exception of use of i386, it looks ok to me. 
Can we just replace i386 with x86_64?    What happens with WinXP machines?

**Comment by bdbcat** [comment]
Rick...
1. Line 115 should be:
set(ARCH "x86_64")
2. Line 102 should be:
set(ARCH "x86_64")

Dave

**Comment by jongough** [comment]
Updated and now going through the build, test, release process.

**Comment by jongough** [comment]
Closed as had to rebase to resolve conflicts. jg_master_take2 is now the pull request to merge

**Pull request closed without merging**
