### PR TITLE
Update otcurrent_pi to v2.8, removed 2.7.7.2

### PR DESCRIPTION
**Pull request by Rasbats**
Somehow Watchdog has appeared in this PR.

### CODE REVIEW

**Comment by Rasbats** [comment]
Thanks again.

**Comment by rgleason** [comment]
Mike, perhaps you did not pull from upstream to get your remote rasbats/plugins updated?
I can fix this as I have another  PR  to Plugins  which fixes the icons.

**Comment by Rasbats** [comment]
Please go ahead. I have not seen the problem at this end.

**Comment by rgleason** [comment]
I didn't see any problem either when I updated, watchdog 2.4.23.2 was still there in metadata and I did not see 2.4.23.0 which caused troubles, as you discovered and reported. Thanks..

**Pull request merged**
