### PR TITLE
updated squiddio icon

### PR DESCRIPTION
**Pull request by mauroc**
latest version with black background

### CODE REVIEW

**Comment by bdbcat** [comment]
Mauro...

In this repo, we store the plugin metadata, and the resulting ocpn-plugins.xml file.
Rick has been building the Squiddio plugin lately.  Please coordinate with him about the plugin release processfor Squiddio.

**Comment by rgleason** [comment]
Mauro,  I'll get on you cloudsmith repos and download your xmls and mix them with the other squidddio env that I've compiled previously.  There will be two versions dependent on environment.

Meanwhile ...You should first make a PR to bdbcat with your configured meta-url to your own plugins  branch: "mc-alpha"   Read the Meta-url  Alpha Catalog  Dev wiki page for more info.

**Comment by rgleason** [comment]
Mauro change the opening and closing  tags according to this. Otherwise there is more work and failure.

Find the form in your setup and change it please!!


<?xml version="1.0" encoding="UTF-8"?>
<plugin version="1">
      <name> squiddio </name>
      <version> 1.2.0 </version>
      <release> 1 </release>
      <summary> Repository of sailing destination waypoints </summary>

**Comment by rgleason** [comment]
Mauro  

Also Flatpak  url is wrong

```
 </description>
    <target>flatpak</target>
    <target-version>18.08</target-version>
    <tarball-url> https://dl.cloudsmith.io/public/mauro-calvi/squiddio-pi/raw/names/squiddio-flatpak-18.08-tarball/versions/1.2.0.1+218.b192cc8/squiddio_pi-1.2.0.1_flatpak-18.08.tar.gz </tarball-url>
    <info-url> https://opencpn.org/OpenCPN/plugins/sQuiddio.html </info-url>
  </plugin>

```

It needs to be fixed.  I am taking flatpak out now.

**Comment by rgleason** [comment]
Mauro,
One other thing, I believe Dave and Leamas have dropped including an icon to simplify the process.
So the icon will be updated by having a new version of squiddio.

You can close this now. OK?  Just you or Dave can close it.

**Comment by mauroc** [comment]
> Mauro,
> One other thing, I believe Dave and Leamas have dropped including an icon to simplify the process.
> So the icon will be updated by having a new version of squiddio.
> 
> You can close this now. OK? Just you or Dave can close it.

Got it - I saw the old icon and thought I'd fix it but...problem solved

**Pull request closed without merging**
