### PR TITLE
Updating to javascript_pi v3.0.0 and removing two now obsolete v2s with late patch + fix for architecture

### PR DESCRIPTION
**Pull request by antipole2**
Resubmitting as have now fixed the missing architecture

### CODE REVIEW

**Comment by antipole2** [comment]
I have fixed the missing x86-64 and pushed it to my Master,
Then cancelled the failed Pull and resubmitted.  But check still fails at same point.
?

**Comment by rgleason** [comment]
Tony,
Aren't you using Shipdriver Template?
Have you updated it to be the most current release version?
I believe Pavel made a change that now requires this designation for x86-64.
I recall it being done for OpenCPN, then he declared that it was now for plugins.
I don't know if he set an xml gatekeeper for this, but I think so.

I also believe Mike and Alec (Shipdriver) were all aware an onboard with this, so I expect that Shipdriver has been so updated.

**Comment by antipole2** [comment]
Have been using sd3.3.0-beta1.
I see latest is sd3.3.0-beta4 but when I update I get errors in the update process, so have reached out to Mike.

**Comment by antipole2** [comment]
Closing as have new try ready

**Pull request closed without merging**
