### PR TITLE
TideFinder beta 1.2 managed

### PR DESCRIPTION
**Pull request by Rasbats**
Testing adding a new beta for the managed version. This uses the new alternative managed workflow developed by Alec Leamas

### CODE REVIEW

**Comment by Rasbats** [comment]
Dave... I seem to be having the same problem as Lennart with adding a plugin to the beta catalog. Can this be resolved at your end?

**Comment by rgleason** [comment]
I think the set-env variable had be dropped  and you need to use something else.

**Comment by Rasbats** [comment]
Thanks. Do you know what I need to use? And where?

**Comment by rgleason** [comment]
Is this helpful?  
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
YOu would need to change set-env in the config.yml file?

**Comment by rgleason** [comment]
You may be right, maybe the Actions code needs to be changed?  
If you did a search for set-actions in your plugin directory, that might determine where the problem is coming from.

**Comment by Rasbats** [comment]
Not finding `set-actions` . It will have to wait for my scripting guru!

**Comment by bdbcat** [comment]
Error corrected.  Root cause:  branch master was updated to remove environment variable usage, as required for github security rules.  Branch Beta had not been updated to follow same logic.  Done now.
Please re-submit your PR, should pass checks now.

**Comment by Rasbats** [comment]
Thanks Dave... working on it shortly.

**Comment by Rasbats** [comment]
Closing this PR to allow a new one.

**Pull request closed without merging**
