### PR TITLE
Two PR

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Comment by rgleason** [comment]
The script must be changed. Dave.

Url validation passed
Processing file: metadata/weather_routing_pi-1.13.45.0-debian-arm64-11-bullseye-arm64.xml
metadata/weather_routing_pi-1.13.45.0-debian-arm64-11-bullseye-arm64.xml:17: element target: Schemas validity error : Element 'target': [facet 'enumeration'] The value 'debian-arm64' is not an element of the set {'all', 'android-arm64', 'android-arm64-v8a', 'android-armeabi-v7a', 'android-armhf', 'darwin', 'darwin-arm64', 'darwin-wx315', 'debian-armhf', 'debian-gtk3-armhf', 'debian-x86_64', 'flatpak-aarch64', 'flatpak-x86_64', 'flatpak-x86_64-wx315', 'mingw', 'mingw-x86_64', 'msvc', 'msvc-64', 'raspbian-armhf', 'ubuntu-armhf', 'ubuntu-gtk3-armhf', 'ubuntu-gtk3-x86_64', 'ubuntu-x86_64'}.
metadata/weather_routing_pi-1.13.45.0-debian-arm64-11-bullseye-arm64.xml fails to validate
..

**Comment by jongough** [comment]
I think the XSD needs an update to add the new target.

**Comment by rgleason** [comment]
Yes, I can't continue pushing.

**Comment by jongough** [comment]
The XSD is provided by OCPN and should be in each branch of plugins. If this does not exist the plugin may not be seen by the user.

**Comment by rgleason** [comment]
Dave can you also add that to Alpha and Beta?

**Comment by bdbcat** [comment]
Already done, at the same time as master.
I can be trained...:)

**Comment by rgleason** [comment]
I am afraid it is the reverse  (:-)

**Comment by rgleason** [comment]
Thanks Dave,  BTW, the main ones are all pushed and finishing building 
https://github.com/jongough/testplugin_pi/issues/177

I am trying to figure out how to get my diverged autopilot_route_pi   in tune with Sean's.  I have separately forked Sean's locally and updated it with FE2 and it finally seems to be building for windows.  My version is also updated and builds everything, so I thought I would copy the local files from sean's version,  into my local to see if that will work.

I also updated pypilot_pi and that seems to be working. So I will try to get those done too.

**Comment by rgleason** [comment]
https://github.com/jongough/testplugin_pi/issues/177
See the list for TP 1.0.213 those are built or building.

The public [OpenCPN  Cloudsmith repository ](https://cloudsmith.io/~opencpn/repos/)  https://cloudsmith.io/~opencpn/repos/

**Comment by bdbcat** [comment]
Rick...
I imported and tested two on flatpak aarch64:  AISRadar, and weather-routing.  Both import, install, and run OK in smoke test.  Ready for the catalog.
Let me know if you reach a dead end on autopilot_route_pi.  I'll take a look.

**Comment by rgleason** [comment]
Great. Will push them all to plugins.

**Pull request merged**
