### PR TITLE
wxfx 1.9.42.0 fix hurricane danger BOS New Orleans, update FE

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Comment by rgleason** [comment]
This is missing https://github.com/rgleason/weatherfax_pi
build-flatpak-arm64
 https://app.circleci.com/pipelines/github/rgleason/weatherfax_pi/320/workflows/de977eb4-3b67-4e8c-bdaf-4176d31b6e7d/jobs/4198   -fails.

and macos  because circleci has partial outage https://app.circleci.com/pipelines/github/rgleason/weatherfax_pi/319/workflows/b392551f-110f-40c3-b18a-537d8c2394a3/jobs/4225

**Comment by rgleason** [comment]
Now is see that we have 2 darwin metadata, so just the build-flatpak-arm64 is missing, due to some changes in the version which have been made which Jon and I are unaware of.

**Comment by jongough** [comment]
It would appear the plugin build process for android and flatpak is in flux. There appear to be changes to defines, new git repositories, changes to widgets, etc. This is not going to be helpful. Just look at the shipdriver master branch. I will have to wait until this stabilises.

**Comment by rgleason** [comment]
Well, Jon, I guess we should just drop that OS from any plugins that are built.  We really don't have any choice.

**Pull request closed without merging**
