### PR TITLE
Updating to javascript_pi v3.0.0 and removing two now obsolete v2s with late patch

### PR DESCRIPTION
**Pull request by antipole2**

### CODE REVIEW

**Comment by antipole2** [comment]
Any idea why this fails?
> Processing file: metadata/javascript-v3.0.0-build-1d-msvc-wx32-10.xml
> metadata/javascript-v3.0.0-build-1d-msvc-wx32-10.xml:22: element target-arch: Schemas validity error : Element 'target-arch': [facet 'enumeration'] The value '' is not an element of the set {'x86_64', 'x86', 'armhf', 'arm64', 'aarch64', 'noarch', 'arm64;x86_64', 'x86_64;arm64'}.
> metadata/javascript-v3.0.0-build-1d-msvc-wx32-10.xml fails to validate

**Comment by bdbcat** [comment]
Show us this file:
metadata/javascript-v3.0.0-build-1d-msvc-wx32-10.xml

**Comment by antipole2** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- https://ci.appveyor.com/project/antipole2/javascript-pi/builds/49513957 -->
<plugin version="1">
  <name> javascript </name>
  <version> v3.0.0-build-1d </version>
  <release> 0 </release>
  <summary> Run JavaScripts in the plugin </summary>

  <api-version> 1.18 </api-version>
  <open-source> yes </open-source>
  <author> Tony Voss </author>
  <source> https://github.com/Antipole2/JavaScript_pi </source>
  <info-url> https://opencpn-manuals.github.io/main/javascript/index.html </info-url>

  <description> This plugin for OpenCPN allows you to run JavaScript and to interact with OpenCPN.
You can use it to script your own enhancements to standard OpenCPN functionality.
See help menu ? for documentation details
 </description>

  <target>msvc-wx32</target>
  <target-version>10</target-version>
  <target-arch></target-arch>
  <tarball-url> https://dl.cloudsmith.io/public/opencpn/javascript-prod/raw/names/javascript-v3.0.0-build-1d-msvc-wx32-10-tarball/versions/v3.0.0-build-1d/javascript-v3.0.0-build-1d_msvc-wx32-10-win32.tar.gz </tarball-url>
  <tarball-checksum> 58add2e6a0d97fdec7d0af99c4f6f45077dc37db118a9479b39dd51cce68d59b </tarball-checksum>
</plugin>
```

**Comment by antipole2** [comment]
Should have
`<target-arch>x86_64</target-arch>`
I think.  Don't know how it got lost.

**Comment by bdbcat** [comment]
As the error message says, target-arch must be
"element of the set {'x86_64', 'x86', 'armhf', 'arm64', 'aarch64', 'noarch', 'arm64;x86_64', 'x86_64;arm64'}."
So, "x86-64" will do it.

**Comment by rgleason** [comment]
Tony,
I just checked cloudsmith prod repos for Javascript Plugin and 
so it looks like it is ok.
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- https://ci.appveyor.com/project/antipole2/javascript-pi/builds/49513957 -->
<plugin version="1">
  <name> javascript </name>
  <version> v3.0.0-build-1d </version>
  <release> 0 </release>
  <summary> Run JavaScripts in the plugin </summary>

  <api-version> 1.18 </api-version>
  <open-source> yes </open-source>
  <author> Tony Voss </author>
  <source> https://github.com/Antipole2/JavaScript_pi </source>
  <info-url> https://opencpn-manuals.github.io/main/javascript/index.html </info-url>

  <description> This plugin for OpenCPN allows you to run JavaScript and to interact with OpenCPN.
You can use it to script your own enhancements to standard OpenCPN functionality.
See help menu ? for documentation details
 </description>

  <target>msvc-wx32</target>
  <target-version>10</target-version>
  <target-arch></target-arch>
  <tarball-url> https://dl.cloudsmith.io/public/opencpn/javascript-prod/raw/names/javascript-v3.0.0-build-1d-msvc-wx32-10-tarball/versions/v3.0.0-build-1d/javascript-v3.0.0-build-1d_msvc-wx32-10-win32.tar.gz </tarball-url>
  <tarball-checksum> 58add2e6a0d97fdec7d0af99c4f6f45077dc37db118a9479b39dd51cce68d59b </tarball-checksum>
</plugin>

```

**Comment by rgleason** [comment]
Have you updated your template?

**Comment by antipole2** [comment]
Don't know how that got lost.  I have patched it and try again.

**Pull request closed without merging**
