### PR TITLE
watchdog 2.4.60.0

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Comment by rgleason** [comment]
Yes, this morning I was trying the android version and when installing a message pops up 

The following plugin has encountered errors during startup.  
This plugin will be uninstalled. Reinstall after updating the catalog.

I am wondering what the blockage might be. I don't think there are many external files that are written to, so we probably aren't violating the new Android enforced file system.

**Comment by bdbcat** [comment]
I'm on it.
Thanks
Dave

**Comment by nocheinpeter** [comment]
Additional info:

Watchdog pi does not start on Android 11, Samsung Galaxy Tab A.
Actual Opencpn app restarts and de-activates the pi.

data/user/0/org.opencpn.opencpn/manPlug/libwatchdog_pi.so
16:39:59.862 MESSAGE plugin_loader.cpp:336 Checking plugin compatibility: /data/user/0/org.opencpn.opencpn/manPlug/libwatchdog_pi.so
16:39:59.862 MESSAGE plugin_loader.cpp:1209 PluginLoader: Loading PlugIn: /data/user/0/org.opencpn.opencpn/manPlug/libwatchdog_pi.so
16:39:59.863 ERROR dlunix.cpp:162 dlopen failed: cannot locate symbol "glBegin" referenced by "/data/data/org.opencpn.opencpn/manPlug/libwatchdog_pi.so"...
16:39:59.863 MESSAGE plugin_loader.cpp:1254 Ignoring blacklisted plugin libwatchdog_pi
16:39:59.864 MESSAGE plugin_loader.cpp:1264 PluginLoader: Cannot load library: /data/user/0/org.opencpn.opencpn/manPlug/libwatchdog_pi.so




Did never try previous versions.

Greetings
Peter

**Comment by rgleason** [comment]
@nocheinpeter   PLease post under this new issue!
https://github.com/OpenCPN/plugins/issues/950

 Thanks.

**Comment by bdbcat** [comment]
Corrected Android plugin load.
PR posted.
#53

**Comment by rgleason** [comment]
@bdbcat   Please see 
https://github.com/OpenCPN/plugins/issues/950#issuecomment-1669468811

**Comment by rgleason** [comment]
Now I see this went into OpenCPN master and is merged.  Humm???

**Pull request merged**
