### PR TITLE
Jg master

### PR DESCRIPTION
**Pull request by jongough**

### CODE REVIEW

**Comment by bdbcat** [comment]
Needs rebase, collision with RGleason commit.

**Comment by jongough** [comment]
This whole process is a nightmare. Trying to get the ocpn-plugins.xml to merge is totally dependant on when the merge attempt it made. When I initially created this pull request it all worked, you then merged another change and it no longer works. I have tried to resolve the issues but, I think, due to time zones it always fails on the internet version. There needs to be a better way of generating this file.

**Comment by bdbcat** [comment]
Jon...
It is always safe to delete an ocpn-plugins.xml file from your local copy, and regenerate from a freshly pulled github master, with your metadata updated.  Probably much quicker than manually fixing the conflicts.
Dave

**Comment by jongough** [comment]
That is not the problem. The real problem is that pulls frequently invalidate other pulls. So I put up a pull against the master and it all passed OK and got the green light. However, you accepted another pull before mine which then invalidated my pull which you then asked me to fix up. This suggests that the whole update process for ocpn-plugins.xml is very fragile and needs fixing up. There is a possibility that adding a main.yml fie to the '.github/workflows' directory that has something like this:
```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
```
to cause the generation of the ocpn-plugins.xml file may be a solution.

**Pull request closed without merging**
