### PR TITLE
Try frcurrents again

### PR DESCRIPTION
**Pull request by Rasbats**
v1.4.1 includes Android

### CODE REVIEW

**Comment by Rasbats** [comment]
Edited the metadata file for msvc to show target-arch. Previously it was blank.

**Comment by Rasbats** [comment]
Check for msvc fails to validate. Can we see if it works?

**Comment by Rasbats** [comment]
Mainly to test my Android work.

**Comment by Rasbats** [comment]
@bdbcat Do you want me to remove this and make a new PR?

**Comment by bdbcat** [comment]
Sorry, slipped into the distant past on my TODO list.

**Comment by Rasbats** [comment]
Many thanks. Now to see if the Android changes work!

**Pull request merged**
