### PR TITLE
AutoTrackRaymarine 1.18.4.0 fails in Win

### PR DESCRIPTION
**Pull request by rgleason**
See this thread please (also android does not build yet)
https://github.com/douwefokkema/AutoTrackRaymarine_pi/issues/22

### CODE REVIEW

**Comment by rgleason** [comment]
Dave,  
Should I change testplugin_pi   API 116 to ---> API 118?
See  https://github.com/jongough/testplugin_pi/issues/322

**Comment by bdbcat** [comment]
Rick...
No.  Plugins should use the minimum plugin API that they require.

**Comment by rgleason** [comment]
What???  My head hurts hearing this.

Does this mean that every plugin API setting should be increased to API118?
Then what happens to OpenCPN 5.6.2 builds?

Does this mean that I should copy the two API 118 files over into testplugin ?
as indicated here
Should I change testplugin_pi API 116 to ---> API 118?
See https://github.com/jongough/testplugin_pi/issues/322

**Comment by rgleason** [comment]
No I guess that would mess up the OpenCPN 5.6.2 builds!

**Pull request merged**
