### PR TITLE
Removing javascript v1.0 metadata

### PR DESCRIPTION
**Pull request by antipole2**

### CODE REVIEW

**Comment by rgleason** [comment]
Tony, you need to update auto and try again I think.

**Comment by antipole2** [comment]
Dave... Oh!  I was trying to remove the v1.0 xml without going all the way through a full build etc. etc.
Mike advised...

>  If your plugins fork is in synch with OpenCPN It can be done with desktop. Remove the xml files from the master branch. Commit/push then make another PR using the master branches.

So if I get my repo in sync with master,  create a branch (it need not be called auto), delete the unwanted xmls, commit and then make a pull request that should work?
I am a real amateur as far as GitHub is concerned.

**Comment by bdbcat** [comment]
So if I get my repo in sync with master, create a branch (it need not be called auto), delete the unwanted xmls, commit and then make a pull request that should work?

Yes

**Comment by antipole2** [comment]
Might I hav resolved conflicts so you can merge?

**Comment by antipole2** [comment]
Dave… The last pull appeared to work and v1.0 no longer appears in the catalogue.
However, I am getting a daily email telling me the nightly check has failed.  Looking at the report it says the  “Check metadata” has failed.

What’s to do?

**Comment by rgleason** [comment]
Tony I am getting a similar message for findit_pi and am a bit confused about it too.   I think you should look at the version number and then determine if that version exists in Cloudsmith or your deploy repos.

**Comment by rgleason** [comment]
Tony I found my Cloudsmith retention settings for the findit-prod repository were limited to 28 days, when days should have been turned off or "0"   I changed that and now have to push a new version to prod, etc.

I also checked Javascript  alpha, beta and prod and the settings are all good.  
alpha is 30 day and 100 packages  and  size limit=0 or off.
beta is  days=0 or off and packages=204  size limit=0
prod is days=0  or off and  packages= 528  and size limit =0 or off

Don't know what is causing your error now.

**Comment by antipole2** [comment]
I am not using ci builds at all - just building the tarball locally.  So the repo should not even know about my new version.
When I cleaned out the metadata for v1.0 I did not use the auto branch as I was not building.  I suspect that has confused it.
Perhaps I should update my plugins repo from OCP Plugins Master?  Or delete the fork left after the pull?

**Comment by rgleason** [comment]
maybe try using "v1.01-beta" until you are ready to deploy? Mike would know better.

**Pull request merged**
