### PR TITLE
Update to add macos wx315 build

### PR DESCRIPTION
**Pull request by jongough**

### CODE REVIEW

**Comment by bdbcat** [comment]
I will merge this, but...
The metadata for "darwin" should be "darwin-wx315".

**Comment by bdbcat** [comment]
See email...

**Comment by jongough** [comment]
No according to the ocpn-plugin.xsd in alpha:
```
<xs:element name="target">
  <xs:simpleType>
    <xs:restriction base = "xs:string">
      <xs:enumeration value = "all"/>
      <xs:enumeration value = "android-arm64"/>
      <xs:enumeration value = "android-arm64-v8a"/>
      <xs:enumeration value = "android-armeabi-v7a"/>
      <xs:enumeration value = "android-armhf"/>
      <xs:enumeration value = "darwin"/>
      <xs:enumeration value = "darwin-arm64"/>
      <xs:enumeration value = "darwin-wx32"/>
      <xs:enumeration value = "debian-armhf"/>
      <xs:enumeration value = "debian-wx32-armhf"/>
      <xs:enumeration value = "debian-gtk3-armhf"/>
      <xs:enumeration value = "debian-x86_64"/>
      <xs:enumeration value = "debian-wx32-x86_64"/>
      <xs:enumeration value = "debian-arm64"/>
      <xs:enumeration value = "debian-wx32-arm64"/>
      <xs:enumeration value = "flatpak-aarch64"/>
      <xs:enumeration value = "flatpak-x86_64"/>
      <xs:enumeration value = "mingw"/> <!-- transitional, see OpenCPN#2061 -->
      <xs:enumeration value = "mingw-x86_64"/>
      <xs:enumeration value = "msvc"/>
      <xs:enumeration value = "msvc-64"/>
      <xs:enumeration value = "msvc-wx32"/>
      <xs:enumeration value = "raspbian-armhf"/>
      <xs:enumeration value = "ubuntu-armhf"/>
      <xs:enumeration value = "ubuntu-gtk3-armhf"/>
      <xs:enumeration value = "ubuntu-gtk3-x86_64"/>
      <xs:enumeration value = "ubuntu-x86_64"/>
      <xs:enumeration value = "ubuntu-wx32-x86_64"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
```

**Comment by jongough** [comment]
This is the problem with mangling xml. If we had each of the items separated we would not have these issues. Making tuples into a target is asking for issues depending on when and who makes the changes.

**Comment by bdbcat** [comment]
Jon, this is how the PIM works in O5.  Impossible to change without instantly breaking 10s of thousands of O5 installations in the field.
Like it or not, we are stuck with our own legacy.

**Pull request merged**
