### PR TITLE
Update to SAR v2.7.3

### PR DESCRIPTION
**Pull request by Rasbats**

### CODE REVIEW

**Comment by Rasbats** [comment]
Dave ...

I thought aarch64 was allowed but circleci check failed? Does an xsd need updating?

`metadata/sar-2.7-flatpak-A64-20.08.xml:20: element target-arch: Schemas validity error : Element 'target-arch': [facet 'enumeration'] The value 'aarch64' is not an element of the set {'x86_64', 'armhf', 'arm64', 'noarch'}.
`

This plugin is using the latest ShipDriver template, worked on by Alec.

Mike

**Comment by bdbcat** [comment]
I guess we are now using "arm64" on all plugins.  Not sure when this changed.
Is it possible to change your plugin to suit?

**Comment by leamas** [comment]
@rasbats: Could you please link to a build, or even better to cloudsmith? I need to see the metadata file...

**Comment by leamas** [comment]
>  guess we are now using "arm64" on all plugins. Not sure when this changed. Is it possible to change your plugin to suit?

Certainly, but it's just not the right thing to do. The Flatpak community uses aarch64, not arm64. Using arm64 on our side  will create all sorts of mess-up when we still must use aarch64 in the repo etc. 

BTW: Debian is the basically the only community using arm64, they are the exception. The rest of the world uses aarch64.

**Comment by Rasbats** [comment]
circleci builds are here:
[https://app.circleci.com/pipelines/github/Rasbats/sar_pi/100/workflows/a51ef6e4-aa69-42d9-aa04-ac0c00540046](https://app.circleci.com/pipelines/github/Rasbats/sar_pi/100/workflows/a51ef6e4-aa69-42d9-aa04-ac0c00540046)

cloudsmith products here:
[https://cloudsmith.io/~opencpn/repos/sar-prod/packages/](https://cloudsmith.io/~opencpn/repos/sar-prod/packages/)

**Comment by leamas** [comment]
Thanks. It looks indeed like https://github.com/OpenCPN/plugins/pull/368 should fix this (knock, knock...)

**Comment by leamas** [comment]
@rasbats: https://github.com/OpenCPN/plugins/pull/368 is merged. Could you please make a new build so we can see what happens?

**Comment by Rasbats** [comment]
New build underway. Closing this PR.

**Comment by Rasbats** [comment]
PR for SAR 2.7 has worked:
[https://github.com/OpenCPN/plugins/pull/369#event-4779137012](https://github.com/OpenCPN/plugins/pull/369#event-4779137012)

**Comment by rgleason** [comment]
Is this a problem for "testplugin"?  
We have for example, https://cloudsmith.io/~opencpn/repos/weatherfax-prod/packages/?q=weatherfax_pi-1.9.16.0

**Comment by leamas** [comment]
Not really.  The basic issue is that we are heading for three flatpak builds in the 5.6.0 cycle and it's when implementing those builds the issue here surfaces. I will file a bug against testplugin pi when we have a better reference setup.

**Pull request closed without merging**
