### PR TITLE
otcurrent-v2.7.7.1

### PR DESCRIPTION
**Pull request by Rasbats**
Ran into upper/lower case problems. This should fix it.

### CODE REVIEW

**Comment by rgleason** [comment]
Mike, should we just be using all lower case in your opinion?

**Comment by Rasbats** [comment]
Rick...
What is causing a problem is that old metadata items are being left in 'ocpn-plugins.xml'. Found 'OTCurrent' as well as 'otcurrent'. This has resulted in an entry appearing in the managed plugins list 'OTCurrent', that is impossible to remove. Just about to ask Dave if a resync is possible. Have not been able to make a pull request to remove this item.

**Comment by rgleason** [comment]
Maybe it is the plugin cache on your machine too?
Mine gets a mess while testing and i have to clear it out!

Do a search to find it. In win it is with the old plugins

**Comment by jongough** [comment]
The main thing here is to make sure you delete the old files in your branch as well as adding the newly downloaded files. If you are doing this on Linux it treats case as important so it happily uses OTCurrent and otcurrent as two different files. If you are doing this on windows it will assume the files are the same. I have had this problem in the past with samba shares when testing with windows but have now forced case consistency i.e. windows sees the difference between the two files and shows them as two files.

The ocpn-plugins.xml build process is running on linux and builds this file based on ALL the files in the metadata directory. It does not care who put the files in there, it just uses them. This then allows developers to delete, modify or add new files and the ocpn-plugins.xml file will always be consistent with what is in the github repository.

I hope this makes sense.

**Comment by rgleason** [comment]
Yes, this is my experience.

**Pull request merged**
