### PR TITLE
v0.2.4.0

### PR DESCRIPTION
**Pull request by LennartG-Sve**
GPS Odometer

### CODE REVIEW

**Comment by rgleason** [comment]
Good!  You got it working.

**Comment by rgleason** [comment]
@bdcat  When using your local and remote "master"  plugins branch to submit metadata files via a PR to opencpn/plugins, what is the user supposed to do to update their remote master branch afterwards?

Does the git Action script automatically keep all the users forked remote "master" branches current with the merged opencpn/plugins master branch?

**Comment by bdbcat** [comment]
Rick...
A simple "git pull origin master" will always bring your local files up to date with the current github repo.
There will be conflicts if you have changed any of your local files before doing this.
So, always, ALWAYS, before you start modifcations to your local metadata files, do a "git pull origin master".

**Comment by rgleason** [comment]
Thanks, that is nice and simple.
Just to be clearer, is origin = my remote repos rgleason/plugins?

If so, the git actions are keeping all forked remote plugin repositories current with opencpn/plugins master branch.

**Comment by rgleason** [comment]
Also, is my rg-master branch being automatically updated or not? (Not necessarily a request). Just would like to know.

**Comment by bdbcat** [comment]
origin is what your see when you do:
"git remote --verbose"
For me, this is:
```
dsr@dsr-HPE-580t:~/Projects/plugins$ git remote --verbose
origin  git@github.com:OpenCPN/plugins.git (fetch)
origin  git@github.com:OpenCPN/plugins.git (push)

```
I don't know what your rg-master branch is, and why you need it.

**Comment by rgleason** [comment]
Thanks, that helps

```
Rick@Dart MINGW64 ~/documents/github/plugins (rg-master)
$ git remote -v
origin  https://github.com/rgleason/plugins.git (fetch)
origin  https://github.com/rgleason/plugins.git (push)
upstream        https://github.com/opencpn/plugins.git (fetch)
upstream        https://github.com/opencpn/plugins.git (push)
```
Is this backwards?  It is how I have setup all my repositories and I have kind of gotten used to it.
I can switch it easily enough with the git remote commands.

Jon, really wanted me to use a separate branch from master like rg-master before the Action script probably, because we where having troubles during development.  I

**Comment by rgleason** [comment]
No wonder it wasn't working, the remotes for my master are

Rick@Dart MINGW64 ~/documents/github (master)
```
$ git remote -v
origin  https://github.com/rgleason/autopilot_route_pi.git (fetch)
origin  https://github.com/rgleason/autopilot_route_pi.git (push)

```

Sorry.

**Comment by bdbcat** [comment]
If it were me, I would discard the fork (rgleason/plugins), and work exclusively with what you are now calling "upstream", i.e. the true master.

**Comment by rgleason** [comment]
OK, thanks

**Comment by rgleason** [comment]
Cloned  OpenCPN/plugins  to  local repository plugins-o  and tried it.

made a new commit  testplugin v1.0.139 and then

```
Rick@Dart MINGW64 ~/documents/github/plugins-o (master)
$ git push origin master
remote: Permission to OpenCPN/plugins.git denied to rgleason.
fatal: unable to access 'https://github.com/OpenCPN/plugins.git/': The requested URL returned error: 403
```

**Comment by bdbcat** [comment]
Well, yes.
You do not have write permissions to OpenCPN/plugins.
You will need to revert to using a fork of the master plugins repo, as you had been doing before, to prepare the PRs
Sorry for the misdirection...
Dave

**Pull request merged**
