### PR TITLE
squiddio 1.3.8.8 + fe2 v1.0.137 + android

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Comment by bdbcat** [comment]
Rick...
Android already includes Squiddio, as unmanaged "system" plugin.
Is this managed version different/better?

**Comment by rgleason** [comment]
I have updated squiddio to frontend2 v1.0.137 which supports android. I don't really know what you have done or why a PR wasn't made. Sorry.

I have been trying to figure out why this failed.

"Processing file: metadata/squiddio_pi-1.3.8.8-ubuntu-x86_64-20.04-focal-gtk3.xml
Error: Process completed with exit code 1."

because it looks fine to  me.

Please explain.

**Comment by rgleason** [comment]
So we have a system that we aren't using complete?  IE Android?
So is there any reason to include android for managed plugins anymore?

**Comment by rgleason** [comment]
Right now I am rebuilding / deploy with a new version number because I think the multiple deploys with previous version due to PR and merges to Mauro and branches is perhaps causing the problem.

**Comment by rgleason** [comment]
So what do you want me to do?  Remove the android xml's?  I am going to be pushing again shortly.

**Comment by rgleason** [comment]
It also fixes flatpak.  I am going to bed.

**Comment by rgleason** [comment]
Also that android version is old, version 7.  no weather bouys etc.

**Comment by rgleason** [comment]
```
Android already includes Squiddio, as unmanaged "system" plugin.
Is this managed version different/better?
```
I think it is better.

**Comment by bdbcat** [comment]
Rick...
1.  Squiddio has been part of Android basic release for a long time.
2.  Have you corrected the build, and tested Squiddio with OA5.2.2 (Import)?  I doubt it will work, since "system" plugins are not designed to be replaced by managed versions with the same common name.  But it might....
Dave

**Comment by rgleason** [comment]
Downloaded https://cloudsmith.io/~opencpn/repos/squiddio-prod/packages/detail/raw/squiddio_pi-1.3.8.9-android-armhf-16-android-armhf-tarball/v1.3.8.9/
directly to Android  Downloads directory, and tried "Import Plugin", I waited a little time, and "Plugin  Imported successfulll. Active Catalog updated. Plugin may be installed or updated now. "
Then when I go up to the Squiddio 0.7 icon it shows  "==User-sourced database of sailing destinations." but no  "Update" button or "install" button. It just has "Preferences" and  "Website"

Below the "unmanaged" Squiddio Icon, there is a box icon with "squiddio 1.3.8.9"  Plugin to download and display points of interest on a chart"   There is an "Install" button.
I hit it.
"Install complete "squiddio 1.3.8.9 successfully installed from cache."  "OK"   Hit  ok.

Now I find a separate "squiddio v1.3.8.9" green puzzle icon that can be enabled, but the toolbar icon does not show.

Is this a common name problem?   We have been using the same common name for squiddio for quite awhile, so I wonder what has happened.  Did it get changed with the android  "Squiddio  0.7" version perhaps?

**Comment by bdbcat** [comment]
Rick..
Good test.  As I suspected, the unmanaged "system" plugins (GRIB, Dashboard, Squiddio/Android, etc.) cannot be replaced by a managed version, even if the common names match. That is why you are getting a duplicate plugin icon. This scenario was never considered relevant, and so was never tested.
The simple solution is to remove the Squiddio unmanaged "system" plugin from the Android package.  That way, the managed plugin that you are building will install and work normally on Android, we hope.

Sometime today (couple of hours, now is not a good time), I will build an Android APK without Squiddio, and upload to Dropbox for you to test.

Thanks
Dave

**Comment by rgleason** [comment]
Dave, thank you.  I am sorry about the added trouble and will certainly give it a try.  As a backup if this does not work, I could just not include the android versions.

**Comment by bdbcat** [comment]
Rick...
No trouble.  I think having Squiddio as a managed plugin is a better idea, anyway.
Check your PM on CruiserForum for a link to 5.2.2(61), for testing.
And please let me know how this goes.  I am trying to release OA5.2.2 tonight...

**Comment by bdbcat** [comment]
Rick...
I tested 1.3.8.9 on Android 5.2.2(61).
It failed.

Please change source code:
squiddio_pi.cpp:1138

```
-                    wxMessageBox(sMsg, wxMessageBoxCaptionStr, wxOK | wxCENTRE | wxSTAY_ON_TOP);
+                    wxMessageBox(sMsg, _T("Message"), wxOK | wxCENTRE | wxSTAY_ON_TOP);

```
Should load after that change.

**Comment by rgleason** [comment]
Downloaded and Installed: 
https://www.dropbox.com/s/oyv5ti6gwc9eb3p/org.opencpn.opencpn-v61%285.2.2%29-release.apk?dl=0

Then installed  

Message when opened

    Opencpn Info
    Incompatible plugin detected:
    /data/data/org.opencpn..opencpn/manPlug/libsquiddio_pi.so
    Plugin [squiddio_pi] version 0.2, and all previous versions is incompatible with this version of OpenCPN.
    OK,

The first time I Import Plugin   squiddio 1.3.8.9

https://cloudsmith.io/~opencpn/repos/squiddio-prod/packages/detail/raw/squiddio_pi-1.3.8.9-android-armhf-16-android-armhf-tarball/v1.3.8.9/


It did not show up in the plugin list.

So I shut down opencpn normally, and reopened.

Then I tried Import Plugin squiddio 1.3.8.9 again. with a success message and squiddio 1.3.8.9 showed up as a box icon

Clicked on squiddio, and picked Install. It installed normally with a succcess message.

Next I found green puzzle squiddio  1.3.8.9 and green puzzle pypilot 0.22.4.0 and oeSenc as a box, I was able to enable squiddio 1.3.8.9   (and also pypilot 0.22.4.0) and then I found vdr_pi 1.26 and enabled that).  I appliied and hit ok and the Vdr icons show in the toolbar, but not pypilot or squiiddio.


I also have watchdog 2.4 enabled and testplugin 1.0 enabled.  and they show in the toolbar.

I tried to download oesenc 4.2.16.7 and it download successfully and installed successfully from cache. Then I tried to enable it and hit OK and I don't find that icon in the toolbar.

I hope this helps.

Rick

**Comment by rgleason** [comment]
bdbcat,  II just saw your post above.  Will do so, but there is also something else going on I think. For example, I could not get pypilot or oesenc to show icons, but I could get vdr to show icons in the toolbar.

Android does not support svg I believe. Maybe it has something to do with that?

**Comment by bdbcat** [comment]
Rick...
Lets go step by step on squiddio.  It fails to load due to the code change suggested above. Please do that first.
Please leave the other plugins aside for the moment, and focus on squiddio.  We need that to release OA 5.2.2.
BTW, oeSENC has no toolbar icon....

**Comment by rgleason** [comment]
Yes will do so.
Made the change specified. It is now building  here master branch  https://github.com/rgleason/squiddio_pi
should end up  in squiddio-prod   https://cloudsmith.io/~opencpn/repos/squiddio-prod/packages/
as I pushed a tag.

**Comment by rgleason** [comment]
Three are already built  for v1.3.9..0  https://cloudsmith.io/~opencpn/repos/squiddio-prod/packages/?q=1.3.9.0*tarball

**Comment by rgleason** [comment]
I probably should have disabled all other builds from inside  circleci  config.yml, but it is a lot of commenting out.

**Comment by rgleason** [comment]
Its done  https://cloudsmith.io/~opencpn/repos/squiddio-prod/packages/detail/raw/squiddio_pi-1.3.9.0-android-armhf-16-android-armhf-tarball/v1.3.9.0/

**Comment by rgleason** [comment]
It acts normally upon Import and Install, but the icon does not show. 
[opencpn.log](https://github.com/OpenCPN/plugins/files/5301866/opencpn.log)

[opencpn.conf.txt](https://github.com/OpenCPN/plugins/files/5301870/opencpn.conf.txt)

Hot off the press, havent looked at it yet.

**Comment by rgleason** [comment]
I am not finding any plugin  tried and failed or shown for libsquiddio. Also there are no "fail"  s found.

**Comment by rgleason** [comment]
Dave, maybe it's not worth having this version for the next release if it is going to cause trouble?

**Comment by rgleason** [comment]
Wait a minute, it installed in my main memory.. I got the wront config and log!

**Comment by rgleason** [comment]
[opencpn.log](https://github.com/OpenCPN/plugins/files/5301972/opencpn.log)
[opencpn.conf.2.txt](https://github.com/OpenCPN/plugins/files/5301973/opencpn.conf.2.txt)

**Comment by rgleason** [comment]
```
6:57:56.058 MESSAGE pluginmanager.cpp:1174 Checking plugin candidate: /data/data/org.opencpn.opencpn/manPlug/libsquiddio_pi.so
16:57:56.058 MESSAGE pluginmanager.cpp:2232 PlugInManager: Loading PlugIn: /data/data/org.opencpn.opencpn/manPlug/libsquiddio_pi.so
16:57:56.072   ERROR dlunix.cpp:162 dlopen failed: cannot locate symbol "_ZN10wxZipEntryC1ERK8wxStringRK10wxDateTimel" referenced by "libsquiddio_pi.so"...
16:57:58.016 MESSAGE pluginmanager.cpp:2291    PlugInManager: Cannot load library: /data/data/org.opencpn.opencpn/manPlug/libsquiddio_pi.so 
```

**Comment by rgleason** [comment]
FYI windows version works ok.   

ERROR dlunix.cpp:162 dlopen failed: cannot locate symbol "_ZN10wxZipEntryC1ERK8wxStringRK10wxDateTimel" referenced by "libsquiddio_pi.so"...

 MESSAGE pluginmanager.cpp:2291    PlugInManager: Cannot load library: /data/data/org.opencpn.opencpn/manPlug/libsquiddio_pi.so 

In looking for these files, I seem to have libsquiddio_pi.so32 and libsquiddio_pi.so64 under org.opencpn.opnecpn/files/plugins/
there is also a squiddio folder with images folder  with all the image used by squiddio, including  "plugin_logo.png" which is used for the toolbar icon, I think.

**Comment by rgleason** [comment]
It looks to me like org.opencpn..opencpn\files\icons is where there are a lot of plugin icons like
TP testpllugin, wmm, Grib, Dashboard,   I don't see the squiddio icon here.

**Comment by bdbcat** [comment]
Rick...
OK, I can see that this is going to need more work.
So, for the meantime, please submit a PR that updates the master catalog for Squiddio, except that it removes Squiddio for Android (2 platforms, armhf and arm64).
I will work on the plugin some, get it working, and then we can add the Android builds to the catalog.
Thanks for your help
Dave

**Comment by rgleason** [comment]
That's a good plan. I realized tomorrow I go to Boston Dr, back at 5pm, no computer.
I belive you are a collaborator.

**Comment by bdbcat** [comment]
Rick...
After a small patch to OA, leading to OA version 5.2.2/62....
And a small patch to Squiddio....
Then Squiddio Version 1.3.9.1 loads and runs OK.
I was confused about which branch was best to work in.  I finally made my changes in "master" branch, and then the result was available at Cloudsmith in the "Beta" catalog branch.
https://dl.cloudsmith.io/public/opencpn/squiddio-beta/raw/names/squiddio_pi-1.3.9.1-android-armhf-16-android-armhf-tarball/versions/1.3.9.1+2252.0f476f9/squiddio_pi-1.3.9.1-android-armhf-16.tar.gz
I'll leave it to you to sort this out.
There are still some GUI issues with Squiddio, dialogs too small, etc.  This is to be expected with a direct port.  So some work is still required.
If you want to test, you will need to download and install OA 5.2.2/62.  This is currently available on the Playstore as a Beta, soon to be released to Production.
Thanks

**Comment by rgleason** [comment]
Thank you Dave. That's great. Will be back to computer at 6pm est.

**Comment by rgleason** [comment]
Morning. I was not able to find the beta version on playstore. Searched "opencpn", "opencpn beta"  an "beta opencpn".  I'll increment to 1.3.10 and push a tag to get it to deploy to squiddio-prod and then make a PR to plugins master

**Comment by bdbcat** [comment]
Rick...
Check your CruiserForum PM for a link to OA 5.2.2/62

I would remove frontend2 branch, if it is obsolete.

**Comment by rgleason** [comment]
Will do so, (also to all the others if has been merged to master, over time).
[Version 1.3.10.0 loads ](https://cloudsmith.io/~opencpn/repos/squiddio-prod/packages/?q=1.3.10.0*tarball)and installs and works in Android.  The screens work on my S4 phone which has a small screen. My finger is a little too big sometimes, but changing settings isn't done that often.   

Now I see after thinking that I installed and enabled squiddio v1.3.10..0, that the plugin list is showing squiddio 1.3.9.0 and when I highlight that there is an update to 1.3.10..0!  So I have updated and got a success message, so now 1.3.10.0 is showing enabled.
Now when I go into preferences, the preferences screen shows in the top left hand quarter of the screen on its own display are, which is just fine as far as I am concerned. It would be nice if the Preferences were to fit the whole screen better so my finger touch does not have to be as careful, but it works ok now on what is a very small screen.  See screenshot below



There are a few little niggling things that I noticed in the Preferences menu and don't know how to get them fixed.
- Text  I cannot seem to turn it off.
- Bouy weather data and Aton  I cannot seem to  turn them on.
- Color adjustments and Fonts and a few other settings don't work yet.
- I don't have Odraw for android installed yet so I haven't tried using those textpoints instead of OpenCPN waypoints.

WIN_20201001_12_28_23_Pro

**Comment by rgleason** [comment]
I have also tried  v1.3.10..0 in Windows and find that when the POI's are OpenCPN waypoints that the text stays on no matter what the  "Text on" setting is.   So this is a universal problem.  When ODraw Textpoints are being used this is not a problem.

In Windows version 1.3.10..0  I found that the bouys are working when both OpenCPN waypoints and ODraw Textpoints are used, so this is some problem caused by Android not accepting the way things are coded.

**Comment by bdbcat** [comment]
Can we get Mauro involved, now that the concept of "managed Squiddio on Android" is proven?
I will have no time in the short term to do anything with this....

**Comment by rgleason** [comment]
Yes, I have written him this morning.

**Comment by rgleason** [comment]
I also tested on Ubuntu 18.04 and found the same small issues:

1.  When the POI's are OpenCPN waypoints that the text stays on no matter what the "Text on" setting is. So this is a universal problem. When ODraw Textpoints are being used this is not a problem.

2. Android  bouys (weather) and AIS not working when checked.  However in the Windows version 1.3.10.0 I found that the bouys are working when both OpenCPN waypoints and ODraw Textpoints are used, so this is some problem caused by Android not accepting the way things are coded.

**Comment by mauroc** [comment]
sorry for jumping in so late
> When the POI's are OpenCPN waypoints that the text stays on no matter what the "Text on" setting is. 

you are correct . This has always been an issue. I remember when I wrote the original code there was no API for turning text on and off programmatically on an OpenCPN waypoint. I don't know if that is still the case - I'll check.

I am running the Android v 5.2.2 off the play store on a Samsung Galaxy 9. Squiddio doesn't show up in the list of plugins, and when I try to download the catalog it shows "Cannot Load data from URL". Not sure if this is the expected behavior - just wanted to flag it. As a result, I can't comment on the issue of weather buoys and AIS icons not showing.

**Comment by bdbcat** [comment]
Mauro..
" Not sure if this is the expected behavior - just wanted to flag it. "
Not expected.  On OpenCPN/Android 5.2.2, master catalog load has been tested and verified to work correctly on all platforms examined so far.
What Version of Android OS are you running on the Galaxy/9?

**Comment by bdbcat** [comment]
Mauro...
Please try catalog update on Android again.  There was a problem with the catalog repo, now fixed.
Thanks
Dave

**Pull request closed without merging**
