### PR TITLE
Try to commit

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Comment by bdbcat** [comment]
Rick....
It worked fine.  Congratulations!
One last nit:  In VDR, the Fedora build is still present.
Otherwise, great!

**Comment by rgleason** [comment]
Dave, I am understanding the process finally. Thanks.
The ocpn-plugins.xml is pushed to my repository, so I have to git pull it.
The conflicts were all from my previous screwups, but I resolved it by copying the correct ocpn-plugins.xml and making a commit for that.
Have removed VDR fedora.

**Comment by jongough** [comment]
ocpn-plugins.xml is in the master branch, when you do a git pull to update your version it will be the current version. Just don't touch it in any way, then the commit/push will not contain it as it is the original version.

**Comment by rgleason** [comment]
So are we supposed to git pull from our remote plugins?   Not git clone the main repos?

**Comment by jongough** [comment]
I think you should git pull upstream master, create a new branch 'rg-master', download all the xml you want from cloudsmith, commit, push your branch to github (your clone), then create a pull request against the upstream. That is what I do when I am not playing around trying to get actions to work. I am messing up my plugins repository at the moment trying to get the validate stuff to only run for the files you have submitted. I am getting closer, but my version of the repository is messed up.

I have used the process quite a few times now and it seems to work for me. I am using Linux with no virus checker and I am now having less issues than I had before. Can you try this stuff out on a linux virtual machine and see if it works. You do seem to have had issues with your virus checker doing stuff. Just a thought.

**Comment by rgleason** [comment]
Jon, I do not believe this is Norton issues at all. I do have a virtual box with ubuntu 18.04 and git.  I can try that, but I'd like to be sure I have the process correct in Windows.

**Comment by rgleason** [comment]
`I think you should git pull upstream master, create a new branch 'rg-master', download all the xml you want from cloudsmith, commit, push your branch to github (your clone), then create a pull request against the upstream`

Jon, when I try to do this exact process, when I try  "push your branch to github (your clone"  I get this message

```
To https://github.com/rgleason/plugins.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/rgleason/plugins.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

So I have to git pull and the ocpn-plugins.xml file has been changed.
Recently, I then downloaded the current ocpn-plugins.xml file from upstream master and added and committed that and then pushed, and bdbcat accepted the PR.

**Comment by jongough** [comment]
It looks like you are trying to push 'master' to the upstream repository. I think you should be pushing a branch of master, creating a pull request on that and then Dave can merge the pull request. Can you try that?

**Comment by jongough** [comment]
I have just done the following commands on windows:
- cd "some testing area"
- mkdir plugin-test
- cd plugin-test
- git clone https://github.com/OpenCPN/plugins
- cd plugins
- git status 
 - shows I am on branch master and up to date with origin/master
 - git branch jg-master-test
- git checkout jg-master-test
- notepad metadata/testplugin_pi-1.0.113.0_ubuntu-x86_64_20.04-focal-gtk3.xml
  - changed a single line by adding a space
- git commit -m "testing" testplugin_pi-1.0.113.0_ubuntu-x86_64_20.04-focal-gtk3.xml
- git remote add mygit https://github.com/jongough/plugins
- git push --set-upstream mygit jg-master-test

I now have jg-master-test on my fork of the OpenCPN/plugins repository. I now click the `Compare & pull request` button which takes me to the OpenCPN/plugins repository pull requests page. I then click on the `Create pull request` button. This creates the actual pull request. 

The git action `CI_Pull` is started. It does give errors as, at the moment, it is checking ALL xml files against the XSD. This does NOT stop the pull request from being merged.

I am working on the CI_Pull action to get it to only check the files provided by that pull request (more difficult than you may assume).

Hope this helps.

**Comment by rgleason** [comment]
`It looks like you are trying to push 'master' to the upstream repository. I think you should be pushing a branch of master, creating a pull request on that and then Dave can merge the pull request. Can you try that?`

No that is not what I am doing.

rgleason/plugins   master branch.
opencpn/plugins  master branch.

from local github plugins folder)
git pull upstream master   (as stated before, 'upstream' remote is opencpn/plugins)
git push origin master   ( 'origin remote is rgleason/plugins)

make necessary metadata changes
commit these changes locally (local github plugins folder)without changing ocpn-plugins.xml
git push origin master
results in this message
```
To https://github.com/rgleason/plugins.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/rgleason/plugins.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by jongough** [comment]
You are still working on the master branch. Try working on a branch from the master and push that. In [https://github.com/OpenCPN/plugins/pull/155#issuecomment-647185595](https://github.com/OpenCPN/plugins/pull/155#issuecomment-647185595) notice the following:
- git branch jg-master-test
- git checkout jg-master-test
I did the whole test on windows and it worked. Playing with master may well cause issues as each merge will regenerate the ocpn-plugins.xml file.

Can you please try the whole process and use a non-master branch for your work.

**Comment by rgleason** [comment]
The fact of the matter is that the process I have been using is "normal" and something is changing my repository (not me) so that when I push to it I get that message saying to git pull.

So what is changing my repository?  rgleason/plugins
https://github.com/rgleason/plugins/commits/master
```
Updating the repository GitHub ocpn-plugins.xml
@actions-user
actions-user committed 12 hours ago  

``` 
https://github.com/rgleason/plugins/commit/d3d1ded40a0e7bab29c861109de8208680b8b73c

So it appears that something called "actions-user" has the right to make a PR and then MERGE it without my permission?

--- 
Under github.com  rgleason/plugins  repository,  Settings > Actions
I can disable Actions


```
Actions permissions
Enable local and third party Actions for this repository

This allows any Action to execute, whether the code for the Action exists within this repository, organization, or a repository owned by a third party.
Enable local Actions only for this repository

This allows any Action to execute as long as the code for the Action exists within this repository or organization.
Disable Actions for this repository

This disallows any Action from running in the repository.

```

Shall I do that?

**Comment by rgleason** [comment]
Why do I need my ocpn-plugins.xml changed automatically if I am pulling from upstream master?

**Comment by jongough** [comment]
You don't, but the process works on the main branches and ignores the other branches. As you are using the master branch (a main branch) the code is running and updating your repository. The change that has just been merged into OpenCPN/plugins should fix this issue so that the update will only occur on that repository and not yours.

**Comment by jongough** [comment]
You may want to leave actions enabled so that the 'Pull' actions still work. This does the validation of xml, but that is up to you.

**Comment by rgleason** [comment]
Good Point,  I guess I will be using your different branch method.

**Pull request merged**
