### PR TITLE
A second attempt at v3.0.5

### PR DESCRIPTION
**Pull request by antipole2**
Previous build had checksum error for msvc binary

### CODE REVIEW

**Comment by antipole2** [comment]
Ah... I tried this to seeifI could check it out before the pull

> $ tools/ocpn-metadata  generate --userdir metadata/ \
>         --destfile ocpn-plugins.xml --force
> $ xmllint --noout ocpn-plugins.xml

Looks like it caused a conflict with ocpn-plugins.xml

**Comment by antipole2** [comment]
Dave... can you resolve this or do I need to do it over again?

**Comment by bdbcat** [comment]
Tony...
Sorry, cannot fix.  The conflicts are in all the javascript_pi checksums, and I do not know which are correct.

**Comment by antipole2** [comment]
Will try again

**Pull request closed without merging**
