### PR TITLE
sar 2.6.1.0

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Comment by rgleason** [comment]
The command I used to push this up was

```
C:\Users\Rick\Documents\GitHub\plugins>git push origin --force
Enumerating objects: 17, done.
Counting objects: 100% (17/17), done.
Delta compression using up to 8 threads
Compressing objects: 100% (15/15), done.
Writing objects: 100% (15/15), 1.70 KiB | 871.00 KiB/s, done.
Total 15 (delta 13), reused 0 (delta 0)
remote: Resolving deltas: 100% (13/13), completed with 2 local objects.
To https://github.com/rgleason/plugins.git
 + bad6877...458be6e master -> master (forced update)
```

Because I got this error again when I tried to push the first time.

```
C:\Users\Rick\Documents\GitHub\plugins>git push origin master
To https://github.com/rgleason/plugins.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/rgleason/plugins.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

```

**Comment by rgleason** [comment]
What is this doing in there?

```
Reading state information...
The following NEW packages will be installed:
  libxml2-utils
0 upgraded, 1 newly installed, 0 to remove and 11 not upgraded.
Need to get 108 kB of archives.
After this operation, 180 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libxml2-utils amd64 2.9.10+dfsg-5+ubuntu18.04.1+deb.sury.org+3 [108 kB]
Fetched 108 kB in 1s (195 kB/s)
Selecting previously unselected package libxml2-utils.
```

Fails again,  windvane has one bad xml, oernc and radar several.

**Comment by bdbcat** [comment]
Rick...
What repo was checked out when you got the failed "push" above?

Also, ignore the error check fails.  Not related to your plugins.

**Comment by rgleason** [comment]
master, always master

**Comment by rgleason** [comment]
Try it maybe you'll get the same message.

C:\Users\Rick\Documents\GitHub\plugins>git push origin master
To https://github.com/rgleason/plugins.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/rgleason/plugins.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


I overcome the problem now by using  git push origin master --force
That is simple, but I still don't know why I have to do that, even when I have done the following:
git pull upstream master
git push origin master   (it goes through)
make changes to metadata xmls only.
commit the changes (don't change ocpn-plugins.xml)
git push origin master
...and I get the error!  Really weird.

**Comment by bdbcat** [comment]
Yes, weird...

Try this, just before the failing push:
$git reset ocpn-plugins.xml
then
$git push origin master

Anyway, your PRs are going through, changes are getting integrated into master catalog.  And that is the most important part.

**Comment by bdbcat** [comment]
If all else fails, you could add ocpn-plugins.xml to your gitignore list.

**Comment by jongough** [comment]
[https://github.com/OpenCPN/plugins/pull/160#issuecomment-647132564](https://github.com/OpenCPN/plugins/pull/160#issuecomment-647132564), to do the testing of the xml the xmllint program has to be installed as it is not available in the standard git (docker) repository. I have changed the process a bit in my testing so that install is separated from the actual test of the xml.

Think of git actions as a flatpak or armhf build process. The install does not impact the actual git repository as it is in a sandbox.

**Comment by rgleason** [comment]
Next time I will try inserting
$git reset ocpn-plugins.xml
$git push origin master

and I'll add a gitiginore   ocpn-plugins.xml
all good ideas.

Jon I still need to install wget and xmllint programs, I tend to be a little reluctant adding new stuff to this laptop as I am starting to run out of space and need to do a big cleanup  cleanout too!   But I will get to it.

**Comment by jongough** [comment]
You really shouldn't have to do anything with your repository for updating plugins apart from not working in the master branch. I have my master pointing to the upstream (to keep it current) and my branch from that pointing to my origin so I can generate pull requests.

If you want to run the download bash script you will need wget as it downloads the web page and processes it for you. If you want to run the validator script you will need xmllint as it processes the xml against the xsd. I have both of them working on windows and have given pointers to the software and how to use it. If you are running short on storage, I am sorry I cannot help you with automation, you will just need to download the files by hand from the website. If I can get the CI_Pull process working properly then that will do the validation for you (using validate_xml.sh) on github.

**Pull request merged**
