### PR TITLE
GPS Odometer 0.7.0.5

### PR DESCRIPTION
**Pull request by LennartG-Sve**
Added support for socketCAN (OpenCPN 5.8 and up). Also added separate data storage for sumlog total distance.

### CODE REVIEW

**Comment by LennartG-Sve** [comment]
It appears that the error in version 0.7.0.4 are causing also this one (0.7.0.5) to fail. Looking in the log appears to show 0.7.0.5 ok.
How do one kill 0.7.0.4?  Now closing for today.

**Comment by rgleason** [comment]
Lennart, When I recently pushed a new version of Autopilot_route, I thought that all the builds were completed and it showed accordingly on github (build dropdown)  yet when I went to the cloudsmith repository, there were these spinning symbols on a number of builds  (which caused my plugins  download_xml_bash.sh command to not pull all the builds) and when I hovered over the cloudsmith spinning symbol the message said that verifying the checksum was not complete,etc.   It was taking so long I went to bed and in the morning everything on Cloudsmith was completed and I was able to add the full 23 metadata files and they were accepted.   

Perhaps your "spinners" on cloudsmith were not complete?

**Comment by rgleason** [comment]
From Checking PR Files

```
Processing file: metadata/gpsodometer_pi-0.7.0.4-debian-arm64-wx32-12-bookworm-arm64.xml
metadata/gpsodometer_pi-0.7.0.4-debian-arm64-wx32-12-bookworm-arm64.xml validates
.E

70 errors detected
Not accessible urls:

metadata/gpsodometer_pi-0.7.0.4-debian-arm64-wx32-12-bookworm-arm64.xml: info-url: 404
h
```

This is for 0.7.0.5  so it is having problems finding the files. I think Cloudsmith has not fully processed the files past checksum etc.

You should just wait and then check cloudsmith to make sure there are no "spinners"  Then push to plugins.

**Comment by LennartG-Sve** [comment]
Rick, I'm extremely careful to ensure everything is in cloudsmith before taking the next step. The problem with the first upload was that the website address was not updated in CMakelists.txt. Correcyed that for release 0.7.0.5 an uploaded that as well but, as the 0.7.0.4 was still there, the errors were apparently carried to 0.7.0.5 as well. 
The log for 0.7.0.5 tells that the previous version is still checked causing the errors. So uploading both in succession ought to fix it.

**Comment by LennartG-Sve** [comment]
Dave, please advise the next step. Not sure how to continue on this.
Version/upload v0.7.0.4 should be removed, including metadata (but how?) as version v0.7.0.5 is likely correct.

**Comment by rgleason** [comment]
Lennart,  Maybe you should just close this and make a new PR with just 0.7.0.5.  Give that a try.

**Comment by LennartG-Sve** [comment]
Rick, thought about that and would happily do it but closing this PR does not seem to remove the PR v0.7.0.4 would have been gone when #886 was closed. Then there are the metadata files, can they just be removed if the PR's stays active?
I am simply not sure how to get out of this mess without creating an even bigger mess.
I will then do a v0.7.1.0 to clearly distinguish the versions.

**Comment by LennartG-Sve** [comment]
Dave and/or Rick, generated a fresh 0.7.1.0 and checked the xml-file and this, correct address,  is in there:
_<info-url>
https://opencpn-manuals.github.io/main/gps-odometer/index.html
</info-url>_

Installed the generated tarball from beta and when clicking the website button in PIM I still get the old invalid address, it is apparently not updated when updating the plugin using a tarball. Have not yet generated prod versions

**Comment by LennartG-Sve** [comment]
Versions 0.7.0.4 and 0,7.0.5 are apparently removed from plugins/metadata. Closing this PR.

**Comment by rgleason** [comment]
OK now try to push again.

**Pull request closed without merging**
