### PR TITLE
weatherfax 1.9.6.0 + weather_routing 1.13.8

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Comment by rgleason** [comment]
This has 74 conflicts I don't feel comfortable resolving.  I git pull upstream twice and then tried to git push origin and was notified I had changes in my remote.  This is very unusual.  I git pull origin and there were changes.  Some action actor had pushed stuff to my repos.

Now there are 74 conflicts.

**Comment by bdbcat** [comment]
Rick...
Please try to create your PR _**WITHOUT**_ including ocpn-plugins.xml.  Just leave it off the commit.
It should be re-created automatically in github by Jon's latest workflow patches.
Dave

**Comment by rgleason** [comment]
ok that is not the normal process to date

**Comment by rgleason** [comment]
I can't now it is forcing me to git pull origin, which is making me resolve all 74 conflicts.
Maybe I can just delete everything and then delete the file again.

**Comment by bdbcat** [comment]
Jon is proposing a new process.
Maybe it will work better.  That is, a contributor (you) does not need to worry about the entire ocpn-plugins.xml.  Just needs to be sure his own metadata is clean and accurate.

**Comment by bdbcat** [comment]
Rick...
To recover at this point, just delete ocpn-plugins.xml from your local repo, then git pull.  Should be no conflicts there.

**Comment by bdbcat** [comment]
So, to be clear, there is no longer any need for you to run
"tools/ocpn-metadata generate...."

**Comment by rgleason** [comment]
Yes, the conflicts in the file were not a problem. I just deleted it and pushed it to my remote. Now will try to create another PR and close this PR.

**Comment by rgleason** [comment]
Dave this is not working unfortunately. I ran check again and recreated ocpn-plugins.xml  then added and committed it.
Then deleted it and made a commit for that. Then tried git push origin master. I got this message again!

Screenshot (804)

Which is the same thing that happened when I got the conflicts, so its fruitless to go that route.

**Comment by rgleason** [comment]
Can't remove the file from edit.

**Comment by rgleason** [comment]
Only way to do this is to try to resolve the conflicts. I wonder if we could just hand off the metadata and forget about the ocpn-plugins.xml which seems problematical the way it is working now.

**Comment by jongough** [comment]
The way to resolve conflicts easily is to checkout the 'master' to another local name, copy the ocpn-plugins.xml file (i.e. save it) to somewhere, checkout your branch and replace the version of ocpn-plugins.xml with the version you saved from the 'master' branch. This is so that you can update the metadata (by using download_xml_bash.sh in windows) and just push the metadata to the remote git. There is now no need to run the ocpn-plugins.xml generation process, in fact you REALLY shouldn't, as it will be created automatically when your pull request is merged into the master (Alpha, Beta and Experimental should also be the same). This is an attempt to solve the issues with conflicting versions. You just need to make sure you are up to date with where the master is now before you start and as you are not changing the ocpn-plugins.xml file it will not be in the push to the repository.

A new process, but hopefully will be easier to use. If you want to check your xml files use the validation script, 'validate_xml.sh' (it will tell you the arguments to give it, and it will show you any errors. This script will, hopefully, be used on git to validate the xml during the pull/merge process.

**Pull request closed without merging**
