### PR TITLE
GPS Odometer v0.3.2.0

### PR DESCRIPTION
**Pull request by LennartG-Sve**
Should now be available on Windows as well plus a set of languages added

### CODE REVIEW

**Comment by bdbcat** [comment]
CI is failing.
NOT merged.
Please advise.

**Comment by LennartG-Sve** [comment]
Can't really figure out what went wrong. 'set-env' is likely from a scrit somewhere. Shall I redo any of the pull requests?

**Comment by jongough** [comment]
It is a change in the way that github handles env variables. There is a line in ./github/workflows/CI_Pull.yml that needs changing. I have created a pull request that may fix this issue (#279).

**Comment by rgleason** [comment]
Thanks, Jon.  Once accepted Lennart may need to resubmit

**Comment by bdbcat** [comment]
Jon's PR to plugin workflow accepted.

**Comment by LennartG-Sve** [comment]
#278 failed due to set-env problem

**Pull request closed without merging**
