### PR TITLE
Twocan PlugIn Version 2.0

### PR DESCRIPTION
**Pull request by TwoCanPlugIn**
Updated version of Twocan plugin.

All metadata files pass schema and url validation checks.

Note, that ocpn-plugin.xsd needs to be updated with a new element to reflect flatpack build for arm processors.

refer to issue #413

### CODE REVIEW

**Comment by bdbcat** [comment]
Cannot merge.
Please change "flatpak-arm64" to "flatpak-aarch64"

**Comment by TwoCanPlugIn** [comment]
OK, Understand.

But where ?

In the config.yaml build file for circle ci ?
In the platform build or cloudsmith upload scripts ?
In one of the the cmake files
or directly in the xml metadata file ?


BTW, There is a second PR.
The appveyor build didn't push the Windows tarballs to the correct cloudsmith repo.
The reason appears to be because I initially used an annotated git tag, which for some reason the appveyor build process interpreted as a branch and subsequently published to the cloudsmith alpha repo.
Solution is to use a lightweight git tag.
Note that all of the circle ci  builds published the tarballs to the correct cloudsmith repo even when an annotated git tag was used.

I appreciate that you & the team are focussing on the next version of OpenCPN with whatever features you deem necessary, and. that the Plugin Manager does make it easy for end users to install plugins, however the ci build process is becoming extremely complicated and fragile, to the extent that I think it will discourage any other developers from contributing.

To date I have used the build scrips from Jon Gough's testplugin which is touted as the "Hello World" plugin for the Plugin Manager. It it is bad enough tracing through the myriad of cmake files, shells scripts and ci/appveyor config files, but having perused the current files used by the Voyage Data Recorder (VDR) plugin build process, it is mind boggling to the extent that it is so obfuscated as to be unusable and unmaintainable.If there is further complexity added to the plugin build process, this may be the last contribution I make.

Thanks.

________________________________

**Comment by rgleason** [comment]
` but having perused the current files used by the Voyage Data Recorder (VDR) plugin build process, it is mind boggling to the extent that it is so obfuscated as to be unusable and unmaintainable.If there is further complexity added to the plugin build process, this may be the last contribution I make.`

Steve,  VDR is uses the ShipDriver format.  What branch were you looking at?

**Comment by jongough** [comment]
The 'frontend2' build process is designed to try and make it as easy as possible for developers to use. There are very few frontend2 files that need to changed by the developer. Frontend2 allows building in the cloud, building locally in an IDE, building locally in docker images, deploying locally whether build in an IDE or in docker, build using the circleci local capabilities, build without a '.git' file structure. Because of this the frontend2 files are a bit complicated to handle the processes. If a developer wants to 'start from scratch' that is their choice, but the cloud build/test process is complicated and more so if you want to do local testing.

Just to be clear, there is no compunction on any developer to use frontend2 as it is only an example which I try to keep up to date with the changes that occur in OCPN and Plugin Manger. You can continue to build with whatever process you deem suitable.

**Pull request merged**
