### PR TITLE
nmeaconverter

### PR DESCRIPTION
**Pull request by RooieDirk**

### CODE REVIEW

**Comment by bdbcat** [comment]
As described in separate email, plugin PRs no longer should include ocpn-plugins.xml.  This file is built automatically by the github system from now.
Please simply remove ocpn-plugins.xml from your PR, and re-submit.
Thanks
Dave

**Comment by rgleason** [comment]
Dave, my experience with submitting metadata files is that no matter what I do 
including git --reset hard upstream/master   I ended up being notified that are changes in my remote repos that I first have to merge.  I have written about this this morning as I have about 4 plugins that need updating. Jon wrote back with the following instructions, which I have not tried ...yet.



Hi Rick,
   Start from scratch with plugins, i.e. create a new folder and re-clone the plugins repository. This gets you a clean starting point, then:

1.     Create a new branch, i.e. rg_master
2.     Use download_xml_bash.sh in git-bash to download your xml files
3.     If you want run the validate_xml.sh process AFTER you have got xmllint working (see previous email)
4.     Git add your new files
5.     Remove any old files of YOURS that you do not want anymore
6.     Git push your changes
7.     Create a pull request on opencpn/plugins for your changes
8.     Have a cup of tea/coffee and do something else whilst Dave accepts your pull
9.     All done

There is nothing else to do. Don't touch/change/update/create anything else. All you need from git is in the cloned repository, you are just adding/deleting the files you are interested in. Don't change/update/delete any other files except the xml you are responsible for in the metadata directory.

Hope this helps
Regards Jon

Regarding running Validate_xml.sh  Jon wrote this.

i Rick,
   As you are running under windows you need to install a ming64 version of xmllint. You can do this by installing msys2 from 'https://www.msys2.org/' then install via 'pacman' xmllint , this is done by issuing 'pacman -S mingw-w64-x86_64-libxml2' on the msys2 command line. The xmllint package will not work at the moment in the gitbash shell (don't know why, but I haven't really looked).

   Once you have xmllint install (check by just issuing 'xmllint' and see what happens) you would issue the command: 'validate_xml.sh weatherfax_pi 1.9.6.0' and if it all is OK it will say 'All files pass xsd check', otherwise it will tell you the errors.

   The command takes the first part of the name of the plugin and the version number, it will check any files in the metadata directory that match. It does not know anything about naming apart from the name part comes first, followed somewhere by a number followed by 'xml'. If you look in the command you will see it is capable of being used by the new 'pull_request' action to identify if there are xml issues.

Regards
   Jon

**Comment by RooieDirk** [comment]
Rick,
I had the same problems and started 2 times from scratch with a complete new fork, but the trick is point 1 in Jon's list. Don't work in the master branch, but create a new one.

**Comment by rgleason** [comment]
Thanks, but I don't think that is the problem. I overcame it by using  --force at the end of the push.

**Comment by jongough** [comment]
I try to never work in the master branch, I do all my work in a another branch just in case I stuff up so I can go back. I only use master branch for merging pull requests (I then get multiple bites at the cherry). Doing this also means that, hopefully, you are not impacted if a change occurs on the remote repository master, i.e. a merge of another pull, as you would then have to do a pull again before pushing. By doing the changes on a branch the pull will only fail if your changes to a file and the changes to the master copy are too extensive for the automated process to work out how to do the merge and will require you to work it out. Then you just pull the master branch, rebase your working branch and push the updates back to your remote.

**Comment by jongough** [comment]
[https://github.com/OpenCPN/plugins/pull/154#issuecomment-647132737](https://github.com/OpenCPN/plugins/pull/154#issuecomment-647132737), I am not sure you should be using `--force` on any push to the remote repositories. If something goes wrong you could mess it up. It should be used with care and understanding of the underlying issues.

**Pull request closed without merging**
