### PR TITLE
Rg master  Watchdog v2.4.12  Frontend2 v1.0.120

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Comment by rgleason** [comment]
Dave this does not look clean to me. 
from my branch rg-master I did git pull upstream master
should I be doing git pull upstream master --force?
to get rid of the previous commits that are all ready merged into ocpn-plugins.xml

This is a process question.

**Comment by bdbcat** [comment]
Looks OK to me.
But in future, best if you make one PR per plugin.  Don't mix two plugins into one PR.

**Comment by rgleason** [comment]
I agree. The first plugin was the one accepted this morning, and it seems to have stuck around and been included in this PR.
What am I doing wrong between making PR's? 

I have been from my local plugins git repository,  on the rg-master branch, done git pull upstream master to stay current, then made my changes to metadata.

**Comment by rgleason** [comment]
There is a notice that the branch has been merged and can be safely deleted. 
Which I have done and my remote repostory branch rg-master was deleted (I checked).
So now should I delete my local branch rg-master?

Then from master branch  git pull origin master
Then  git checkout -b rg-master again?
and make the next metadata changes in rg-master?

**Comment by bdbcat** [comment]
Rick...
That would work.
The problem we had with your last PR was a collision with another PR pending at the same time.  Required me to sort it out.  This will happen from time to time.  No worries.

**Pull request merged**
