### PR TITLE
add weatherfax rm watchdog VDR weather_routing

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Comment by rgleason** [comment]
Dave, when I checked the files  watchdog, weather_routing and VDR all showed 404 errors, so I removed those plugins, then added weatherfax which do not have 404, but have not been tested in Ubuntu etc.

Unfortunately ocpn_draw files all have 404's too, but I did not remove those.
The reporting for using check.bat is much better. Thank you whoever fixed it.
I found that VDR, watchdog and weather_routing all had 404 now so I removed them.
These weatherfax xmls that I added all seem to check out, but I tried to build a current alpha Opencpn in Ubuntu 18.04
and weatherfax was not working well.  I hope this is because of my build. Please advise. 


C:\Users\Rick\Documents\GitHub\plugins>python tools\check-metadata-urls
.........................................................................
.............................EEEEEEEEEEEEE...............................
..........................................
188 urls checked, 13 errors
https://dl.cloudsmith.io/public/jon-gough/ocpn_draw_pi-beta/raw/names/ocpn_draw_pi-1.6.70-darwin-10.13.6-macos-tarball/versions/1.6.70.0+588.60aaf7f/ocpn_draw_pi-1.6.70.0_darwin-10.13.6-macos.tar.gz: 404
https://dl.cloudsmith.io/public/jon-gough/ocpn_draw_pi-beta/raw/names/ocpn_draw_pi-1.6.70-debian-10-buster-tarball/versions/1.6.70.0+581.60aaf7f/ocpn_draw_pi-1.6.70.0_debian-10-buster.tar.gz: 404
https://dl.cloudsmith.io/public/jon-gough/ocpn_draw_pi-beta/raw/names/ocpn_draw_pi-1.6.70-fedora-29-fedora-tarball/versions/1.6.70.0+579.60aaf7f/ocpn_draw_pi-1.6.70.0_fedora-29-fedora.tar.gz: 404
https://dl.cloudsmith.io/public/jon-gough/ocpn_draw_pi-beta/raw/names/ocpn_draw_pi-1.6.70-flatpak-18.08-flatpak-tarball/versions/1.6.70.0+580.60aaf7f/ocpn_draw_pi-1.6.70.0_flatpak-18.08.tar.gz: 404
https://dl.cloudsmith.io/public/jon-gough/ocpn_draw_pi-beta/raw/names/ocpn_draw_pi-1.6.70-mingw-10-mingw-tarball/versions/1.6.70.0+585.60aaf7f/ocpn_draw_pi-1.6.70.0_mingw-10-mingw.tar.gz: 404
https://dl.cloudsmith.io/public/jon-gough/ocpn_draw_pi-beta/raw/names/ocpn_draw_pi-1.6.70-msvc-10.0.14393-MSVC-tarball/versions/1.6.70.0+391.60aaf7f/ocpn_draw_pi-1.6.70.0_msvc-10.0.14393-MSVC.tar.gz: 404
https://dl.cloudsmith.io/public/jon-gough/ocpn_draw_pi-beta/raw/names/ocpn_draw_pi-1.6.70-raspbian-10-buster-armhf-tarball/versions/1.6.70.0+587.60aaf7f/ocpn_draw_pi-1.6.70.0_raspbian-10-buster-armhf.tar.gz: 404
https://dl.cloudsmith.io/public/jon-gough/ocpn_draw_pi-beta/raw/names/ocpn_draw_pi-1.6.70-raspbian-9.4-stretch-armhf-tarball/versions/1.6.70.0+583.60aaf7f/ocpn_draw_pi-1.6.70.0_raspbian-9.4-stretch-armhf.tar.gz: 404
https://dl.cloudsmith.io/public/jon-gough/ocpn_draw_pi-beta/raw/names/ocpn_draw_pi-1.6.70-ubuntu-14.04-trusty-tarball/versions/1.6.70.0+578.60aaf7f/ocpn_draw_pi-1.6.70.0_ubuntu-14.04-trusty.tar.gz: 404
https://dl.cloudsmith.io/public/jon-gough/ocpn_draw_pi-beta/raw/names/ocpn_draw_pi-1.6.70-ubuntu-16.04-xenial-tarball/versions/1.6.70.0+586.60aaf7f/ocpn_draw_pi-1.6.70.0_ubuntu-16.04-xenial.tar.gz: 404
https://dl.cloudsmith.io/public/jon-gough/ocpn_draw_pi-beta/raw/names/ocpn_draw_pi-1.6.70-ubuntu-18.04-bionic-gtk3-tarball/versions/1.6.70.0+582.60aaf7f/ocpn_draw_pi-1.6.70.0_ubuntu-18.04-bionic-gtk3.tar.gz: 404
https://dl.cloudsmith.io/public/jon-gough/ocpn_draw_pi-beta/raw/names/ocpn_draw_pi-1.6.70-ubuntu-18.04-bionic-tarball/versions/1.6.70.0+584.60aaf7f/ocpn_draw_pi-1.6.70.0_ubuntu-18.04-bionic.tar.gz: 404
https://dl.cloudsmith.io/public/jon-gough/ocpn_draw_pi-beta/raw/names/ocpn_draw_pi-1.6.70-ubuntu-20.04-focal-tarball/versions/1.6.70.0+589.60aaf7f/ocpn_draw_pi-1.6.70.0_ubuntu-20.04-focal.tar.gz: 404

**Comment by bdbcat** [comment]
Rick...
Not sure what went wrong.
But please remember:  ALWAYS PULL FROM MASTER before creating your own PR.  Someone else (i.e.Jon) may have made a PR that I merged, but you will not have this merge data until you do a pull yourself.  Thus, you get Jon's stale data, with 404's.
I fixed and accepted this PR, with VDR removed and WeatherFax added.

**Comment by rgleason** [comment]
I did pull from upstream.
so how would I have gotten an old version?

**Comment by rgleason** [comment]
PS would you mind trying weatherfax in some version of Ubuntu when you get a chance?
Also what version of O should we be using now?

**Comment by bdbcat** [comment]
Rick...
You should be using current github master, built locally.
Is VDR OK now?

**Comment by bdbcat** [comment]
Rick...
On Ubuntu 16.04, WeatherFax, I get "Invalid XML file".
I have never run WeatherFax before, so have no idea what it should say...

**Comment by rgleason** [comment]
Darn. I am going to have to remove them. It works for Windows with import plugin. Will track it down.

**Comment by rgleason** [comment]
Oh Invalid XML File comes up, then it copies the xml file to the user area I believe.
Then if you pick  Retrieve  > Internet  and select  say NOAA and then BOSTON and then try to download a fax.

**Comment by bdbcat** [comment]
Rick...
OK, yes it works.  Boston Sea State retrieved OK.

**Comment by rgleason** [comment]
Great. Thanks.  VDR reworked coming up.  Trying the Cloudsmith Opencpn group repository this time.

**Comment by rgleason** [comment]
> You should be using current github master, built locally.
> Is VDR OK now?

Ok, I am going to have to rebuild my ubuntu 18.04 opencpn as it is not working right.
It builds, and I am going to check it next after updating frontend1 with Arch.

**Pull request merged**
