### PR TITLE
testplugin 1.0.225 + bdbcat deb o571 blds

### PR DESCRIPTION
**Pull request by rgleason**
I haven't actually built testplugin for years. It took some trials to get it working with the authorization keys etc..  This should be 23 new files.

### CODE REVIEW

**Comment by rgleason** [comment]
Now what?
```
metadata/testplugin_pi-1.0.225.0-ubuntu-x86_64-22.04-jammy.xml fails to validate
Error: Process completed with exit code 3.
```

From the metadata file:  The tarball-url works. The target "ubuntu-wx32-x86_64" is correct as far as I know.
```
<target>ubuntu-wx32-x86_64</target>
<build-target>ubuntu</build-target>
<build-gtk>gtk3</build-gtk>
<target-version>22.04</target-version>
<target-arch>x86_64</target-arch>
<tarball-url>
https://dl.cloudsmith.io/public/opencpn/testplugin-prod/raw/names/testplugin_pi-1.0.225.0-ubuntu-x86_64-wx32-22.04-jammy-tarball/versions/v1.0.225/testplugin_pi-1.0.225.0-ubuntu-x86_64-22.04-jammy.tar.gz
</tarball-url>
```

**Comment by bdbcat** [comment]
Yes, should be "wx32" (NOT "W32")
Fix that, and it should verify

**Comment by rgleason** [comment]
Ok, will do that. But what about the ubuntu one above?

**Comment by rgleason** [comment]
The target "ubuntu-wx32-x86_64" is correct as far as I know. Yes, ubuntu-x86_64 exists in the set but I don't see ubuntu-wx32-x86_64 --Does xml set have to be added to, or does the testplugin target have to change?

**Comment by bdbcat** [comment]
I fixed that in the xsd.  All correct now.

**Comment by rgleason** [comment]
> Yes, should be "wx32" (NOT "W32")
> Fix that, and it should verify

I will fix in the metadata file, but not sure  where to fix that in the cmake files.

**Comment by rgleason** [comment]
"ubuntu-wx32-x86_64" 
> I fixed that in the xsd. All correct now.
Thanks.

**Comment by rgleason** [comment]
Ok that checked out now. 
Any thoughts on msvc-wx32? 
I don't think you touched that.
I think it should show as "wx32" in the file name too, rather than "32".

**Comment by bdbcat** [comment]
No good to change wx32 in metadata directly.  Breaks the workflow.
Change in config.yml, line 598
        - WXVERSION: 32   ->        - WXVERSION: wx32

**Comment by rgleason** [comment]
Any thoughts on msvc-wx32?
I don't think you touched that.
I think it should show as "wx32" in the file name too, rather than "32".

Dave, I look at config.yml and find that a change in Line 598

```
Change in config.yml, line 598
- WXVERSION: 32 -> - WXVERSION: wx32
```
may not be the standard way to do this in TP. The reason I say this is
look at the macOS  entries where they are also

https://github.com/rgleason/testplugin_pi/blob/master/.circleci/config.yml
 
  build-macos:
        macos:
            xcode: "12.5.1"
        environment:
        - OCPN_TARGET:  macos
        - CLOUDSMITH_PKG_EXT: pkg
        - DEPLOY_USE_ORB: true
        - WXVERSION: 312   <------------------

   build-macos-wx32:
        macos:
            xcode: "12.5.1"
        environment:
        - OCPN_TARGET:  macos
        - CLOUDSMITH_PKG_EXT: pkg
        - DEPLOY_USE_ORB: true
        - WXVERSION: 32   <------------------

   build-msvc-2022:
        executor: win/server-2022
        environment:
        - OCPN_TARGET: MSVC
        - MSVC_VERSION: 2022
        - WXVERSION: 32  <------------------------


https://github.com/rgleason/testplugin_pi/blob/master/ci/circleci-build-macos.sh

Line 18
if [ -n "$WXVERSION" ] && [ "$WXVERSION" -eq "32" ]; then
    echo "Building for WXVERSION 32";
    WX_URL=https://download.opencpn.org/s/Djqm4SXzYjF8nBw/download
    WX_DOWNLOAD=/tmp/wx321_opencpn50_macos1010.tar.xz
    WX_EXECUTABLE=/tmp/wx321_opencpn50_macos1010/bin/wx-config
    WX_CONFIG="--prefix=/tmp/wx321_opencpn50_macos1010"
    MACOSX_DEPLOYMENT_TARGET=10.10
else
    echo "Building for WXVERSION 312";
    WX_URL=https://download.opencpn.org/s/rwoCNGzx6G34tbC/download
    WX_DOWNLOAD=/tmp/wx312B_opencpn50_macos109.tar.xz
    WX_EXECUTABLE=/tmp/wx312B_opencpn50_macos109/bin/wx-config
    WX_CONFIG="--prefix=/tmp/wx312B_opencpn50_macos109"
    MACOSX_DEPLOYMENT_TARGET=10.9
fi

Note there is also a new-macos.sh
https://github.com/rgleason/testplugin_pi/blob/master/ci/circleci-build-macos-new.sh


**Why doesn't the "wx" get used with the WXVERSION down below?**

https://github.com/rgleason/testplugin_pi/blob/master/ci/circleci-build-msvc.bat

:
:: Build the msvc artifacts
::
set "SCRIPTDIR=%~dp0"
set "GIT_HOME=C:\Program Files\Git"
if "%CONFIGURATION%" == "" set "CONFIGURATION=RelWithDebInfo"

**set wx_vers="wx%WXVERSION%"   <----------------------NOTE**
echo Building %wx_vers%

PATH %SCRIPTDIR%.local\bin;%PATH%
dir %SCRIPTDIR%..
dir %SCRIPTDIR%..\msvc
call "%SCRIPTDIR%..\msvc\win_deps" %wx_vers%
path %SCRIPTDIR%.local\bin;%PATH%;"C:\Program Files\CMake\bin"
call "%SCRIPTDIR%..\cache\wx-config.bat"

**Comment by rgleason** [comment]
A little experiment:


C:\Users\fcgle\source\testplugin_pi>set "WXVERSION=32"

C:\Users\fcgle\source\testplugin_pi>set wx_vers="wx%WXVERSION%

C:\Users\fcgle\source\testplugin_pi>echo.%wx_vers%
"wx32  <---Missing "

C:\Users\fcgle\source\testplugin_pi>set wx_vers="wx%WXVERSION%"

C:\Users\fcgle\source\testplugin_pi>echo.%wx_vers%
"wx32"   <----OK

**Comment by rgleason** [comment]
Looking at the windows build here https://ci.appveyor.com/project/rgleason/testplugin-pi/builds/46029480/job/6svs01keto2g7cuo
I realize that the file name is also missing the "wx" in "wx32" and that appveyor.yml is being used, not the batch file.

So looking at appveyor.yml  (which does not use circleci-build-msvc.bat) 
https://github.com/rgleason/testplugin_pi/blob/master/appveyor.yml
at line 64 

```
    - image: Visual Studio 2022
  install:
    - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars32.bat"
    - set WX_VER=32   <--- This should be wx32
    - set WXWIN=C:\wxWidgets-3.2.1
```

**Comment by rgleason** [comment]
So that is what I will try.

**Comment by bdbcat** [comment]
Hold on.  Don't hack.  I'm looking at this now.

**Comment by rgleason** [comment]
I just did it. Sorry.

**Comment by rgleason** [comment]
It is building here  https://github.com/rgleason/testplugin_pi

Appveyor has built msvc-wx32 . v1.0.225.1

https://cloudsmith.io/~opencpn/repos/testplugin-prod/packages/?q=1.0.225.1+metadata

https://cloudsmith.io/~opencpn/repos/testplugin-prod/packages/detail/raw/testplugin_pi-1.0.225.1-msvc-x86_64-wx32-10.0.17763-MSVC-metadata/v1.0.225.1/

It has the "wx32" in the name and the metadata looks right to me.

```
<target>msvc-wx32</target>
<build-target>msvc</build-target>
<build-gtk></build-gtk>
<target-version>10.0.17763</target-version>
<target-arch>x86_64</target-arch>
<tarball-url>
https://dl.cloudsmith.io/public/opencpn/testplugin-prod/raw/names/testplugin_pi-1.0.225.1-msvc-x86_64-wx32-10.0.17763-MSVC-tarball/versions/v1.0.225.1/testplugin_pi-1.0.225.1-msvc-x86_64-wx32-10.0.17763-MSVC.tar.gz
```

**Comment by bdbcat** [comment]
Yes, I agree.  That is the correct spot to set this variable.
So, I think it is all set now, if you undo my earlier path to WXVERSION.
A fresh build of all?

**Comment by rgleason** [comment]
Dave I am not sure what  "earlier patch to WXVERSION" you are referring too?
There might be some commits here that might be what you have identified, but nothing with WXVERSION, I believe.
https://github.com/rgleason/testplugin_pi/commits/master 

Let me know. I can undo what you want, ...or I can just push this minor version and see how it does 1.0.225.1  It is done building.

**Comment by rgleason** [comment]
If this proves to be OK, I will do a fresh build.
Also are there some that I should really remove to avoid confusion?

A. flatpak-x86_64-18.08-flatpak.xml <- No longer needed
A. raspbian-armhf-9.13-stretch-armhf.xml <- No longer needed
C. ubuntu-x86_64-22.04-jammy.xml <- Remove, jammy must be wx32
D. ubuntu-x86_64-20.04-gtk3-focal-gtk3.xml<- Not needed, covered by debian-x86_64-11  (have this now)
E. ubuntu-armhf-20.04-gtk3-focal-armhf.xml<- Not needed, covered by debian-armhf-11-bullseye-armhf.xml  (have this now)
F. ubuntu-armhf-18.04-buster-armhf.xml <- Not needed, covered by debian-armhf-10-buster-armhf.xml   (have this now)
G. ubuntu-x86_64-18.04-bionic.xml <- Not needed, covered by debian-x86_64-10-buster.xml  (have this now)
H. ubuntu-x86_64-18.04-gtk3-bionic-gtk3.xml<- Not needed, covered by debian-x86_64-10-buster.xml  (have this now)

There are exactly three builds that we need today missing:

    debian-x86_64-11   <----YES
    debian-arm64-10    <----YES
    ubuntu-wx32-x86_64-22.04, special case for jammy. <----YES but without the "-wx32" !!!!

We do have file which is going to the right target
-ubuntu-x86_64-22.04-jammy.xml   with <target>ubuntu-wx32-x86_64</target> and  <build-target>ubuntu</build-target>
but is not named  -ubuntu**-wx32**-x86_64-22.04-jammy.xml

Any others in this table?
https://github.com/jongough/testplugin_pi/issues/284

**Comment by bdbcat** [comment]
"ubuntu-wx32-x86_64-22.04, special case for jammy. <----YES but without the "-wx32" !!!!"
Metadata name does not matter to me.  Nor to OCPN.  Only the contents matter.  In this case, there is no name confusion.  We will never build for jammy without wx32, anyway.
I would leave the redundant ubuntu builds in place until we have finished verifying that this plugin (tp) loads on ALL the desired targets.
I'll merge now, and we can test with real reproducible results.

**Comment by bdbcat** [comment]
Next step, after testing, is a full rebuild, version bump, possible removal of redundant ubuntu builds.
Please keep in mind that if you are trying to "fix" any FE2 plugin functional issues for current O562, you will need to retain the older ubuntu builds for these  plugins.  So do not be in a hurry to remove them...

**Comment by rgleason** [comment]
Thanks Dave, for ALL of your help!!!

**Comment by rgleason** [comment]
I think this is a good point and will keep it in mind. There are several plugins in this category.

> Please keep in mind that if you are trying to "fix" any FE2 plugin functional issues for current O562, you will need to retain the older ubuntu builds for these plugins. So do not be in a hurry to remove them, until O58 ships...

**Comment by jongough** [comment]
If you want to build only for 5.7.x then just comment out the unneded builds at the start of the config.yml . Can you please create a pull request against my testplugin_pi repository so I can see what you have done and merge it back into my master?
I will be maintained the old build scripts for a little while until OCPN 5.8.x beds in. I will also be using them to build OD with the changes needed for wx32 and back porting them to the current version. I hope the XSD allows for the old builds as I want to keep my version numbers consistent as well as capabity across the current platforms.

**Comment by rgleason** [comment]
Jon, you can make your own PR from mine, using the Pull tool in your remote github account.
At https://github.com/jongough/testplugin_pi
Set your branch to "updates" on the left.
See  "Pull Requests"  hit that.
Then New pull requests.
Then be sure to hit "Compare across forks" several times while setting branches and forks and making absolutely certain that you are creating the compare you want. and eventually, the PR you want.
https://github.com/jongough/testplugin_pi
There is a sample one.
https://github.com/jongough/testplugin_pi/pull/285
You can clean up my commit mess with interactive squashing
https://garrytrinder.github.io/2020/03/squashing-commits-using-interactive-rebase

**Comment by rgleason** [comment]
Jon, also why not try testplugin 1.0.225.1 in the PIM Beta Catalog and let us know which OS its working for?

**Comment by jongough** [comment]
I currently do not have OCPN 5.7.1 installed on my available machines, I only have 5.6 on a Pi which I am using for navigation. I am not in a position to do testing for a couple of weeks.

**Pull request merged**
