### PR TITLE
photolayer v3.1.21.0

### PR DESCRIPTION
**Pull request by Rasbats**
Unable to use CircleCI to build a MingW version. 
Undefined symbols:
'undefined reference to `_imp___wassert''.

### CODE REVIEW

**Comment by bdbcat** [comment]
Mike...
Is this plugin ready for primetime?  Should we add it to the standard list in opencpn.org downloads page, and remove the Beta reference?

**Comment by Rasbats** [comment]
Maybe better wait a bit. I will update the manual IDC and at the same time make an updated version which references the user manual. I wlll make a reference to PhotoLayer on the forum, which may provide some more testing on a range of systems. I have no idea if FlatPak will work, for instance. Had to do a lot of editing to include libgeotiff and libtiff in the CircleCI builds.

**Comment by bdbcat** [comment]
I have a different view.
My opinion is that if it is in the master catalog, it should be regard as "curated", and ready for user download.  And so, also present on the opencpn.org download page as a "fully capable citizen".

Of course, nothing is perfect, and bugs will happen.  But we will get more testing from average users if it looks like a Production-ready plugin.

**Comment by Rasbats** [comment]
On MacOSX, Windows and Ubuntu I am satisfied it is ready. Please can you add the plugin to the standard list on the website. Users will find it and ceratainly let us know if there are problems. Thanks.

**Pull request merged**
